import React, { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Home, FolderOpen, ListChecks, RefreshCcw, BarChart3, Building2, Settings, Menu, X, Upload, CheckCircle2, AlertTriangle, Search, ChevronDown, WalletCards, Landmark, Sparkles, ArrowUpRight, ArrowDownRight } from 'lucide-react'
import './styles.css'

const BRL = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const fmt = v => BRL.format(Number(v || 0))

const demo = {
  company: { id:'demo', name:'Encantê Natural' },
  summary: { balance: 5731.62, inflow: 11096.69, outflow: 13113.60, pending: 12, revenue: 10601, result: -6999 },
  months: [2379,6490,10562,19005,14445,19278,10601],
  files: [
    {name:'Extrato PagBank Julho.pdf',type:'Extrato bancário',count:35,status:'Importado'},
    {name:'Extrato Nubank Julho.pdf',type:'Extrato bancário',count:48,status:'Importado'},
    {name:'Fatura Nubank Agosto.pdf',type:'Fatura cartão',count:34,status:'Revisar'},
    {name:'Vendas PagBank Maio.pdf',type:'Vendas/maquineta',count:16,status:'Importado'}
  ],
  tx: [
    {date:'13/07/2026',description:'Transferência PagSeguro → Nubank',amount:5000,type:'ENTRADA',category:'Transferência entre contas',confidence:100},
    {date:'13/07/2026',description:'Pagamento de fatura',amount:-5519.35,type:'SAIDA',category:'Cartão de crédito',confidence:96},
    {date:'06/07/2026',description:'LWSA S A',amount:-120,type:'SAIDA',category:'Sistemas e tecnologia',confidence:88},
    {date:'23/07/2026',description:'EPLACE COPIADORA E GRAFICA RAPIDA',amount:-133.2,type:'SAIDA',category:'Impressos e gráfica',confidence:72},
    {date:'22/07/2026',description:'ARMARINHOS LIDER',amount:-89,type:'SAIDA',category:'Materiais / insumos',confidence:66},
    {date:'02/08/2026',description:'Google Ads',amount:-467.11,type:'SAIDA',category:'Marketing e anúncios',confidence:99}
  ]
}

function Logo({compact=false}){return <div className="brand"><img src="/logo-mark.svg"/><div className={compact?'hide-mobile':''}><strong>Claria</strong><span>gestão simples</span></div></div>}

function Kpi({title,value,sub,tone='neutral',icon}){return <div className={'kpi '+tone}><div className="kpi-head"><span>{title}</span>{icon}</div><strong>{value}</strong><small>{sub}</small></div>}

function MiniChart({values}){const max=Math.max(...values);return <div className="mini-chart">{values.map((v,i)=><div key={i} className="bar-wrap"><div className="bar" style={{height:`${Math.max(8,(v/max)*100)}%`}}/><span>M{i+1}</span></div>)}</div>}

function App(){
 const [page,setPage]=useState('inicio'); const [menu,setMenu]=useState(false); const [data,setData]=useState(demo); const [search,setSearch]=useState(''); const [uploading,setUploading]=useState(false); const folderRef=useRef(); const fileRef=useRef();
 useEffect(()=>{fetch('/api/dashboard').then(r=>r.ok?r.json():Promise.reject()).then(x=>setData(x)).catch(()=>{})},[])
 const tx=useMemo(()=>data.tx.filter(t=>t.description.toLowerCase().includes(search.toLowerCase())||t.category.toLowerCase().includes(search.toLowerCase())),[data,search])
 async function upload(files){ if(!files?.length)return; setUploading(true); const fd=new FormData(); [...files].forEach(f=>fd.append('files',f,f.webkitRelativePath||f.name)); try{const r=await fetch('/api/import',{method:'POST',body:fd}); const j=await r.json(); alert(j.message||'Importação concluída'); const d=await fetch('/api/dashboard').then(r=>r.json()); setData(d)}catch(e){alert('Não foi possível enviar agora.')} finally{setUploading(false)} }
 const nav=[['inicio',Home,'Início'],['arquivos',FolderOpen,'Arquivos'],['lancamentos',ListChecks,'Lançamentos'],['conciliacao',RefreshCcw,'Conciliação'],['gestao',BarChart3,'Gestão']]
 return <div className="shell">
  <aside className={menu?'sidebar open':'sidebar'}><div className="side-top"><Logo/><button className="icon-btn close" onClick={()=>setMenu(false)}><X/></button></div><div className="company"><Building2/><div><small>Empresa</small><b>{data.company?.name||'Minha empresa'}</b></div><ChevronDown/></div><nav>{nav.map(([id,I,label])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}}><I size={20}/>{label}</button>)}</nav><div className="side-bottom"><button><Settings size={19}/>Configurações</button><span>Claria v0.1.0</span></div></aside>
  <main><header><button className="icon-btn mobile" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{nav.find(n=>n[0]===page)?.[2]}</h1><p>{page==='inicio'?'Sua empresa em uma visão simples.':'Informações organizadas para você decidir.'}</p></div><div className="master-chip">MASTER</div></header>
  {page==='inicio'&&<section className="content"><div className="hero"><div><span className="eyebrow">VISÃO DO MÊS</span><h2>Olá! Estes são os números que merecem sua atenção.</h2></div><button className="primary" onClick={()=>setPage('arquivos')}><Upload size={18}/>Atualizar dados</button></div><div className="kpis"><Kpi title="Saldo disponível" value={fmt(data.summary.balance)} sub="nas contas identificadas" icon={<WalletCards/>}/><Kpi title="Entradas" value={fmt(data.summary.inflow)} sub="no período" tone="good" icon={<ArrowUpRight/>}/><Kpi title="Saídas" value={fmt(data.summary.outflow)} sub="no período" tone="bad" icon={<ArrowDownRight/>}/><Kpi title="Precisa revisar" value={`${data.summary.pending} itens`} sub="classificação ou conciliação" tone="warn" icon={<AlertTriangle/>}/></div><div className="grid2"><div className="card"><div className="card-title"><div><small>EVOLUÇÃO</small><h3>Entradas mensais</h3></div><span>2026</span></div><MiniChart values={data.months}/></div><div className="card attention"><div className="card-title"><div><small>ATENÇÃO</small><h3>O que fazer agora</h3></div><Sparkles/></div><div className="todo"><CheckCircle2/><div><b>Arquivos processados</b><span>{data.files.length} fontes reconhecidas</span></div></div><div className="todo warn"><AlertTriangle/><div><b>{data.summary.pending} itens para revisar</b><span>Confirme só o que o sistema não reconheceu.</span></div></div><button className="text-btn" onClick={()=>setPage('lancamentos')}>Revisar agora →</button></div></div></section>}
  {page==='arquivos'&&<section className="content"><div className="hero"><div><span className="eyebrow">FONTES DE DADOS</span><h2>Coloque os arquivos na pasta da empresa. A Claria organiza.</h2><p>PDF, Excel e CSV. O sistema tenta reconhecer o formato antes de pedir sua ajuda.</p></div></div><div className="upload-card"><div className="upload-icon"><FolderOpen/></div><div><h3>Pasta da empresa</h3><p>Escolha a pasta onde ficam extratos, vendas, compras e caixa.</p></div><div className="upload-actions"><button className="primary" onClick={()=>folderRef.current.click()} disabled={uploading}>{uploading?'Lendo...':'Escolher pasta'}</button><button className="secondary" onClick={()=>fileRef.current.click()}>Selecionar arquivos</button></div><input ref={folderRef} type="file" multiple webkitdirectory="" directory="" hidden onChange={e=>upload(e.target.files)}/><input ref={fileRef} type="file" multiple accept=".pdf,.xlsx,.xls,.csv" hidden onChange={e=>upload(e.target.files)}/></div><div className="card table-card"><div className="card-title"><div><small>ÚLTIMAS LEITURAS</small><h3>Arquivos reconhecidos</h3></div></div><div className="table">{data.files.map((f,i)=><div className="tr" key={i}><div className="file-name"><div className="file-dot">{f.name.split('.').pop().toUpperCase()}</div><div><b>{f.name}</b><span>{f.type}</span></div></div><span>{f.count} registros</span><span className={f.status==='Importado'?'badge ok':'badge review'}>{f.status}</span></div>)}</div></div></section>}
  {page==='lancamentos'&&<section className="content"><div className="hero"><div><span className="eyebrow">CAIXA</span><h2>Lançamentos</h2><p>O que foi reconhecido entra pronto. Você revisa somente as dúvidas.</p></div></div><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Buscar descrição ou categoria" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="secondary">Só pendentes</button></div><div className="card table-card"><div className="table tx-table"><div className="tr head"><b>Data</b><b>Descrição</b><b>Categoria</b><b>Valor</b></div>{tx.map((t,i)=><div className="tr" key={i}><span>{t.date}</span><div><b>{t.description}</b><span>{t.confidence>=90?'Classificado automaticamente':'Sugestão para confirmar'}</span></div><span className="category">{t.category}</span><b className={t.amount>=0?'money in':'money out'}>{fmt(t.amount)}</b></div>)}</div></div></section>}
  {page==='conciliacao'&&<section className="content"><div className="hero"><div><span className="eyebrow">CONCILIAÇÃO</span><h2>O sistema cruza o que você vendeu com o que realmente entrou.</h2></div></div><div className="kpis"><Kpi title="Conciliados" value="86%" sub="automáticos" tone="good"/><Kpi title="Prováveis" value="9 itens" sub="confirmar correspondência" tone="warn"/><Kpi title="Sem par" value="3 itens" sub="precisam de atenção" tone="bad"/></div><div className="card"><div className="match"><div><small>VENDA / RECEBIMENTO</small><b>PagBank Crédito Mastercard</b><span>Venda bruta R$ 266,55 • taxa R$ 6,58</span></div><div className="match-line">→</div><div><small>BANCO</small><b>Recebimento líquido</b><span>R$ 259,97</span></div><span className="badge ok">Conciliado</span></div></div></section>}
  {page==='gestao'&&<section className="content"><div className="hero"><div><span className="eyebrow">GESTÃO</span><h2>Resultado em linguagem simples.</h2></div></div><div className="kpis"><Kpi title="Faturamento" value={fmt(data.summary.revenue)} sub="mês atual"/><Kpi title="Resultado operacional" value={fmt(data.summary.result)} sub="mês atual" tone={data.summary.result>=0?'good':'bad'}/><Kpi title="Margem de contribuição" value="55%" sub="último mês completo" tone="warn"/><Kpi title="Reserva estimada" value="R$ 17 mil" sub="referência do relatório"/></div><div className="grid2"><div className="card"><div className="card-title"><div><small>DRE RESUMIDA</small><h3>Como o resultado se forma</h3></div></div>{[['Receita bruta',10601],['(-) Deduções e custos',-4770],['Margem de contribuição',5831],['(-) Despesas operacionais',-12830],['Resultado',-6999]].map((r,i)=><div className={'dre '+(i===4?'total':'')} key={i}><span>{r[0]}</span><b>{fmt(r[1])}</b></div>)}</div><div className="card attention"><div className="card-title"><div><small>LEITURA GERENCIAL</small><h3>Resumo</h3></div><Sparkles/></div><p>O mês mostra queda de entrada e pressão de custos. A prioridade é proteger caixa, revisar despesas e acompanhar o ritmo de vendas semanalmente.</p><small>Na v0.1 este texto é demonstrativo. A análise por IA será ativada somente quando houver chave configurada.</small></div></div></section>}
  </main></div>
}

createRoot(document.getElementById('root')).render(<App/>)
