import pdf from 'pdf-parse'
const money=s=>{if(!s)return null;let n=String(s).replace(/R\$/g,'').replace(/\s/g,'').replace(/\./g,'').replace(',','.');const neg=n.includes('-');n=n.replace(/[^0-9.]/g,'');const v=Number(n||0);return neg?-v:v}
const brDate=(d)=>{const [a,b,c]=d.split('/');return new Date(`${c}-${b}-${a}T12:00:00-03:00`)}
export function detectPdf(text){const t=text.toUpperCase();if(t.includes('RELATÓRIO DE VENDAS')&&t.includes('CÓDIGO NSU'))return 'PAGBANK_SALES';if(t.includes('EXTRATO DA CONTA')&&t.includes('PAGSEGURO'))return 'PAGBANK_STATEMENT';if(t.includes('SALDO FINAL DO PERÍODO')&&t.includes('MOVIMENTAÇÕES'))return 'NUBANK_STATEMENT';if(t.includes('FATURA')&&t.includes('TRANSAÇÕES DE'))return 'NUBANK_CARD';return 'GENERIC_PDF'}
function parsePagBankStatement(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const out=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/^(\d{2}\/\d{2}\/\d{4})$/);if(!m)continue;const desc=lines[i+1]||'';const valLine=[lines[i+2],lines[i+3],lines[i+4]].find(x=>/^-?R\$\s?[\d.]+,\d{2}$/.test(x));if(!valLine||/saldo do dia/i.test(desc))continue;const amount=money(valLine);out.push({occurredAt:brDate(m[1]),description:desc,amount,direction:amount>=0?'ENTRADA':'SAIDA',raw:{source:'pagbank_statement'}})}return out}
function parsePagBankSales(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const out=[];for(let i=0;i<lines.length;i++){const d=lines[i].match(/^(\d{2}\/\d{2}\/\d{4})\s+(\d{2}:\d{2})$/);if(!d)continue;const window=lines.slice(Math.max(0,i-8),i+10);const type=window.find(x=>/(Crédito|Débito|Boleto|Pix)/i.test(x))||'Venda PagBank';const vals=window.filter(x=>/^R\$\s?[\d.]+,\d{2}$/.test(x)).map(money);if(vals.length<1)continue;const gross=vals[0],fee=vals[1]??0,net=vals[2]??(gross-fee);out.push({occurredAt:new Date(`${d[1].split('/').reverse().join('-')}T${d[2]}:00-03:00`),description:type,amount:gross,direction:'ENTRADA',grossAmount:gross,feeAmount:fee,netAmount:net,raw:{source:'pagbank_sales'}})}return dedupe(out)}
function parseNubankCard(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[];let year=2026;for(const line of lines){const m=line.match(/^(\d{2})\s+(JAN|FEV|MAR|ABR|MAI|JUN|JUL|AGO|SET|OUT|NOV|DEZ).*?(.+?)\s+R\$\s?([\d.]+,\d{2})$/i);if(!m)continue;const months={JAN:1,FEV:2,MAR:3,ABR:4,MAI:5,JUN:6,JUL:7,AGO:8,SET:9,OUT:10,NOV:11,DEZ:12};const month=months[m[2].toUpperCase()];out.push({occurredAt:new Date(`${year}-${String(month).padStart(2,'0')}-${m[1]}T12:00:00-03:00`),description:m[3],amount:-money(m[4]),direction:'SAIDA',raw:{source:'nubank_card'}})}return out}
function parseNubankStatement(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[];let currentDate=null;for(let i=0;i<lines.length;i++){const dm=lines[i].match(/^(\d{2})\s+(JAN|FEV|MAR|ABR|MAI|JUN|JUL|AGO|SET|OUT|NOV|DEZ)\s+(\d{4})$/i);if(dm){const mo={JAN:1,FEV:2,MAR:3,ABR:4,MAI:5,JUN:6,JUL:7,AGO:8,SET:9,OUT:10,NOV:11,DEZ:12}[dm[2].toUpperCase()];currentDate=new Date(`${dm[3]}-${String(mo).padStart(2,'0')}-${dm[1]}T12:00:00-03:00`);continue}if(!currentDate)continue;if(/^(Transferência|Pagamento de boleto|Pagamento de fatura)/i.test(lines[i])&&!/^Total/i.test(lines[i])){let desc=lines[i];let amount=null;for(let j=i+1;j<Math.min(i+8,lines.length);j++){if(/^[-+]?\s?[\d.]+,\d{2}$/.test(lines[j])){amount=money(lines[j]);break}if(/Saldo do dia|Total de/.test(lines[j]))break;desc+=' '+lines[j]}if(amount!==null){const sent=/enviada|pagamento/i.test(desc);if(sent)amount=-Math.abs(amount);out.push({occurredAt:currentDate,description:desc.slice(0,240),amount,direction:amount>=0?'ENTRADA':'SAIDA',raw:{source:'nubank_statement'}})}}}return out}
const dedupe=arr=>{const s=new Set;return arr.filter(x=>{const k=`${x.occurredAt?.toISOString()}|${x.description}|${x.amount}`;if(s.has(k))return false;s.add(k);return true})}
export async function parsePdf(buffer){const {text}=await pdf(buffer);const kind=detectPdf(text);let transactions=[];if(kind==='PAGBANK_STATEMENT')transactions=parsePagBankStatement(text);else if(kind==='PAGBANK_SALES')transactions=parsePagBankSales(text);else if(kind==='NUBANK_CARD')transactions=parseNubankCard(text);else if(kind==='NUBANK_STATEMENT')transactions=parseNubankStatement(text);return {kind,transactions,textPreview:text.slice(0,500),confidence:transactions.length?88:35}}
