import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import multer from 'multer'
import crypto from 'crypto'
import path from 'path'
import fs from 'fs'
import { fileURLToPath } from 'url'
import { initDb,pool,companyId } from './db.js'
import { parsePdf } from './parsers/pdf.js'
import { parseTabular } from './parsers/tabular.js'
import { classify } from './services/classify.js'

const __dirname=path.dirname(fileURLToPath(import.meta.url)); const app=express(); const PORT=process.env.PORT||3000; const mb=Number(process.env.MAX_UPLOAD_MB||20); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:mb*1024*1024,files:100}})
app.use(cors()); app.use(express.json({limit:'2mb'}));
const demo={company:{id:'demo',name:'Encantê Natural'},summary:{balance:5731.62,inflow:11096.69,outflow:13113.60,pending:12,revenue:10601,result:-6999},months:[2379,6490,10562,19005,14445,19278,10601],files:[{name:'Extrato PagBank Julho.pdf',type:'Extrato bancário',count:35,status:'Importado'},{name:'Extrato Nubank Julho.pdf',type:'Extrato bancário',count:48,status:'Importado'},{name:'Fatura Nubank Agosto.pdf',type:'Fatura cartão',count:34,status:'Revisar'},{name:'Vendas PagBank Maio.pdf',type:'Vendas/maquineta',count:16,status:'Importado'}],tx:[{date:'13/07/2026',description:'Transferência PagSeguro → Nubank',amount:5000,type:'ENTRADA',category:'Transferência entre contas',confidence:100},{date:'13/07/2026',description:'Pagamento de fatura',amount:-5519.35,type:'SAIDA',category:'Cartão de crédito',confidence:96},{date:'06/07/2026',description:'LWSA S A',amount:-120,type:'SAIDA',category:'Sistemas e tecnologia',confidence:88},{date:'23/07/2026',description:'EPLACE COPIADORA E GRAFICA RAPIDA',amount:-133.2,type:'SAIDA',category:'Impressos e gráfica',confidence:72},{date:'22/07/2026',description:'ARMARINHOS LIDER',amount:-89,type:'SAIDA',category:'Materiais / insumos',confidence:66},{date:'02/08/2026',description:'Google Ads',amount:-467.11,type:'SAIDA',category:'Marketing e anúncios',confidence:99}]}
app.get('/api/health',(req,res)=>res.json({ok:true,version:'0.1.0',db:Boolean(pool)}))
app.get('/api/dashboard',async(req,res)=>{if(!pool)return res.json(demo);try{const cid=await companyId();const [co,tx,files]=await Promise.all([pool.query('SELECT id,name FROM companies WHERE id=$1',[cid]),pool.query(`SELECT occurred_at,description,amount,direction,category,classification_confidence FROM transactions WHERE company_id=$1 ORDER BY occurred_at DESC LIMIT 100`,[cid]),pool.query(`SELECT name,kind,record_count,status FROM source_files WHERE company_id=$1 ORDER BY created_at DESC LIMIT 20`,[cid])]);if(!tx.rowCount&&!files.rowCount)return res.json({...demo,company:co.rows[0]||demo.company});const inflow=tx.rows.filter(x=>Number(x.amount)>0).reduce((a,x)=>a+Number(x.amount),0),outflow=Math.abs(tx.rows.filter(x=>Number(x.amount)<0).reduce((a,x)=>a+Number(x.amount),0)),pending=tx.rows.filter(x=>!x.category||x.category==='A classificar').length;res.json({company:co.rows[0],summary:{balance:inflow-outflow,inflow,outflow,pending,revenue:inflow,result:inflow-outflow},months:demo.months,files:files.rows.map(f=>({name:f.name,type:f.kind,count:f.record_count,status:f.status==='IMPORTED'?'Importado':'Revisar'})),tx:tx.rows.map(t=>({date:t.occurred_at?new Date(t.occurred_at).toLocaleDateString('pt-BR'):'',description:t.description,amount:Number(t.amount),type:t.direction,category:t.category||'A classificar',confidence:Number(t.classification_confidence||0)}))})}catch(e){console.error(e);res.json(demo)}})
app.post('/api/import',upload.array('files',100),async(req,res)=>{if(!req.files?.length)return res.status(400).json({message:'Nenhum arquivo recebido.'});if(!pool)return res.json({message:`${req.files.length} arquivo(s) lido(s). Configure DATABASE_URL para persistir os registros.`});const cid=await companyId();let imported=0,duplicates=0,records=0,review=0;for(const f of req.files){try{const hash=crypto.createHash('sha256').update(f.buffer).digest('hex');const exists=await pool.query('SELECT id FROM source_files WHERE company_id=$1 AND hash=$2',[cid,hash]);if(exists.rowCount){duplicates++;continue}const ext=path.extname(f.originalname).toLowerCase();let parsed;if(ext==='.pdf')parsed=await parsePdf(f.buffer);else if(['.xlsx','.xls','.csv'].includes(ext))parsed=parseTabular(f.buffer);else continue;const sf=await pool.query(`INSERT INTO source_files(company_id,name,hash,kind,status,record_count,confidence) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[cid,f.originalname,hash,parsed.kind,parsed.confidence<70?'REVIEW':'IMPORTED',parsed.transactions.length,parsed.confidence]);for(const t of parsed.transactions){const c=await classify(t.description,cid);if(c.category==='A classificar')review++;await pool.query(`INSERT INTO transactions(company_id,source_file_id,occurred_at,description,normalized_party,direction,amount,gross_amount,fee_amount,net_amount,category,classification_confidence,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[cid,sf.rows[0].id,t.occurredAt,t.description,c.normalized_party,t.direction,t.amount,t.grossAmount??null,t.feeAmount??null,t.netAmount??null,c.category,c.confidence,t.raw||{}])}imported++;records+=parsed.transactions.length}catch(e){console.error('import error',f.originalname,e)}}res.json({message:`Importação concluída: ${imported} arquivo(s), ${records} registro(s). ${duplicates?duplicates+' duplicado(s) ignorado(s). ':''}${review?review+' item(ns) para revisar.':''}`})})
app.post('/api/classification-rules',async(req,res)=>{if(!pool)return res.status(503).json({message:'Banco não configurado'});const cid=await companyId();const {pattern,category,scope='COMPANY'}=req.body;await pool.query(`INSERT INTO classification_rules(scope,company_id,pattern,category,confidence) VALUES($1,$2,$3,$4,100)`,[scope,scope==='GLOBAL'?null:cid,String(pattern).toUpperCase(),category]);res.json({ok:true})})
const dist=path.resolve(__dirname,'../../client/dist');if(fs.existsSync(dist)){app.use(express.static(dist));app.get('*',(req,res)=>res.sendFile(path.join(dist,'index.html')))}
initDb().then(()=>app.listen(PORT,()=>console.log(`Claria v0.1.0 on :${PORT}`))).catch(e=>{console.error('DB init failed',e);app.listen(PORT,()=>console.log(`Claria sem DB on :${PORT}`))})
