import crypto from 'node:crypto'
import path from 'node:path'
import * as XLSX from 'xlsx'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { pool, getCompany, ensureDefaultChart, findAccountByName, getChartAccounts } from './db.js'
import { createSession, authPayload, hashPassword } from './auth.js'
import { parsePdf } from './parsers/pdf.js'
import { parseTabular } from './parsers/tabular.js'
import { classify } from './services/classify.js'

const n=(v:any)=>Number(v||0)
const pad=(v:any)=>String(v).padStart(2,'0')
const clean=(v:any)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'')
const dateOnly=(v:any)=>{if(!v)return null;const d=v instanceof Date?v:new Date(v);if(Number.isNaN(d.getTime())){const s=String(v),m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);return m?`${m[3]}-${pad(m[2])}-${pad(m[1])}`:null}return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
const money=(v:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n(v))
const DOC_TYPES:any={
  BANK_STATEMENT:'Extrato Bancário',
  CARD_MACHINE_STATEMENT:'Extrato Maquineta Cartão',
  CREDIT_CARD_INVOICE:'Fatura Cartão de Crédito',
  PAYABLES:'Contas a Pagar',
  RECEIVABLES:'Contas a Receber'
}

async function collectUploads(req:any){const files:any[]=[];for await(const part of req.files()){files.push({buffer:await part.toBuffer(),originalname:part.filename||'arquivo',mimetype:part.mimetype||'application/octet-stream'})}req.uploadedFiles=files}
function numberValue(v:any){if(typeof v==='number')return Math.abs(v);const s=String(v??'').replace(/R\$\s?/gi,'').replace(/\s/g,'');const normalized=s.includes(',')?s.replace(/\./g,'').replace(',','.'):s;return Math.abs(Number(normalized.replace(/[^0-9.-]/g,''))||0)}
function fingerprint(cid:string,kind:string,row:any){return crypto.createHash('sha256').update([cid,kind,row.customer||row.supplier||'',row.description||'',row.issueDate||'',row.dueDate||'',Number(row.amount||0).toFixed(2),row.invoiceRef||''].join('|')).digest('hex')}

async function ensureAccount(cid:string,name:string,direction:'ENTRADA'|'SAIDA'){
  if(!name||name==='A classificar')return null
  const existing=await findAccountByName(cid,name);if(existing)return existing
  const revenue=direction==='ENTRADA',section=revenue?'RECEITA_BRUTA':'DESPESAS_OPERACIONAIS',type=revenue?'REVENUE':'EXPENSE',parentName=revenue?'Receitas':'Despesas operacionais'
  const parent=await pool!.query(`SELECT id FROM chart_accounts WHERE company_id=$1 AND active=true AND is_group=true AND upper(name)=upper($2) LIMIT 1`,[cid,parentName])
  const order=await pool!.query(`SELECT COALESCE(max(dre_order),100)::int m FROM chart_accounts WHERE company_id=$1`,[cid])
  const r=await pool!.query(`INSERT INTO chart_accounts(company_id,name,parent_id,account_type,dre_section,dre_order,is_group,active) VALUES($1,$2,$3,$4,$5,$6,false,true) RETURNING id,name,dre_section`,[cid,name,parent.rows[0]?.id||null,type,section,n(order.rows[0]?.m)+1])
  return r.rows[0]
}

function parseModelSpreadsheet(buffer:Buffer,kind:'PAYABLES'|'RECEIVABLES'){
  const wb=XLSX.read(buffer,{type:'buffer',cellDates:true}),rowsOut:any[]=[]
  const common:any={description:['DESCRICAO','HISTORICO','TITULO'],issue:['DATA_EMISSAO','EMISSAO','DATA'],due:['VENCIMENTO','DATA_VENCIMENTO','DT_VENCIMENTO'],amount:['VALOR','VALOR_TITULO','VLR','TOTAL'],category:['CATEGORIA','CLASSIFICACAO','PLANO_DE_CONTAS','CONTA'],payment:['FORMA_PAGAMENTO','MEIO_PAGAMENTO'],invoice:['NUMERO','NUMERO_DOCUMENTO','NF','NOTA_FISCAL','CODIGO'],document:['CNPJ','CPF','DOCUMENTO','CPF_CNPJ']}
  const party=kind==='PAYABLES'?['FORNECEDOR','FAVORECIDO','BENEFICIARIO','RAZAO_SOCIAL','NOME']:['CLIENTE','PAGADOR','SACADO','RAZAO_SOCIAL','NOME']
  for(const sheet of wb.SheetNames){const rows:any[]=XLSX.utils.sheet_to_json(wb.Sheets[sheet],{defval:''});if(!rows.length)continue;const headers=Object.keys(rows[0]),find=(aliases:string[])=>headers.find(h=>aliases.includes(clean(h))),cols:any={};for(const k of Object.keys(common))cols[k]=find(common[k]);cols.party=find(party);if(!cols.due||!cols.amount)continue
    for(const r of rows){const amount=numberValue(r[cols.amount]),dueDate=dateOnly(r[cols.due]);if(!amount||!dueDate)continue;rowsOut.push({party:String(r[cols.party]||'').trim(),document:String(r[cols.document]||'').trim(),description:String(r[cols.description]||r[cols.party]||(kind==='PAYABLES'?'Conta a pagar':'Conta a receber')).trim(),issueDate:dateOnly(r[cols.issue])||dueDate,dueDate,amount,category:String(r[cols.category]||'').trim()||null,paymentMethod:String(r[cols.payment]||'').trim()||null,invoiceRef:String(r[cols.invoice]||'').trim()||null,raw:{sheet,row:r}})}
  }
  return rowsOut
}

async function insertPayable(cid:string,row:any,sourceFileId:string|null,company:any){
  const fake={description:row.description||row.party||'Conta a pagar',amount:-Math.abs(n(row.amount)),direction:'SAIDA'},c=await classify(fake,cid,company),category=row.category||c.category||'A classificar',account=await ensureAccount(cid,category,'SAIDA'),fp=fingerprint(cid,'PAYABLES',{supplier:row.party,...row})
  const tx=await pool!.query(`INSERT INTO transactions(company_id,source_file_id,occurred_at,competence_at,due_at,description,normalized_party,counterparty_document,direction,amount,category,account_id,classification_confidence,classification_status,classification_source,payment_method,financial_status,dre_impact,cash_impact,accounting_role,raw) VALUES($1,$2,$3::date,$3::date,$4::date,$5,$6,$7,'SAIDA',$8,$9,$10,$11,$12,$13,$14,'OPEN',true,false,'PAYABLE',$15::jsonb) RETURNING id`,[cid,sourceFileId,row.issueDate,row.dueDate,row.description,String(row.party||'').toUpperCase()||null,row.document||null,-Math.abs(n(row.amount)),category,account?.id||c.account_id||null,row.category?100:c.confidence,row.category?'CONFIRMED':c.status,row.category?'FILE_MODEL':c.source,row.paymentMethod||null,JSON.stringify({source:'payables_v070',...row.raw})])
  const r=await pool!.query(`INSERT INTO payables(company_id,source_file_id,transaction_id,origin_type,supplier,supplier_document,description,issue_date,due_date,amount,category,account_id,classification_status,classification_source,payment_status,payment_method,invoice_ref,fingerprint,raw) VALUES($1,$2,$3,'FILES',$4,$5,$6,$7::date,$8::date,$9,$10,$11,$12,$13,'OPEN',$14,$15,$16,$17::jsonb) ON CONFLICT(company_id,fingerprint) DO NOTHING RETURNING id`,[cid,sourceFileId,tx.rows[0].id,row.party||null,row.document||null,row.description,row.issueDate,row.dueDate,Math.abs(n(row.amount)),category,account?.id||c.account_id||null,row.category?'CONFIRMED':c.status,row.category?'FILE_MODEL':c.source,row.paymentMethod||null,row.invoiceRef||null,fp,JSON.stringify(row.raw||{})])
  if(!r.rowCount)await pool!.query(`DELETE FROM transactions WHERE id=$1`,[tx.rows[0].id])
  return Boolean(r.rowCount)
}

async function insertReceivable(cid:string,row:any,sourceFileId:string|null,company:any){
  const fake={description:row.description||row.party||'Conta a receber',amount:Math.abs(n(row.amount)),direction:'ENTRADA'},c=await classify(fake,cid,company),category=row.category||c.category||'Receita de vendas',account=await ensureAccount(cid,category,'ENTRADA'),fp=fingerprint(cid,'RECEIVABLES',{customer:row.party,...row})
  const tx=await pool!.query(`INSERT INTO transactions(company_id,source_file_id,occurred_at,competence_at,due_at,description,normalized_party,counterparty_document,direction,amount,category,account_id,classification_confidence,classification_status,classification_source,payment_method,financial_status,dre_impact,cash_impact,accounting_role,raw) VALUES($1,$2,$3::date,$3::date,$4::date,$5,$6,$7,'ENTRADA',$8,$9,$10,$11,$12,$13,$14,'OPEN',true,false,'RECEIVABLE',$15::jsonb) RETURNING id`,[cid,sourceFileId,row.issueDate,row.dueDate,row.description,String(row.party||'').toUpperCase()||null,row.document||null,Math.abs(n(row.amount)),category,account?.id||c.account_id||null,row.category?100:c.confidence,row.category?'CONFIRMED':c.status,row.category?'FILE_MODEL':c.source,row.paymentMethod||null,JSON.stringify({source:'receivables_v070',...row.raw})])
  const r=await pool!.query(`INSERT INTO receivables(company_id,source_file_id,transaction_id,origin_type,customer,customer_document,description,issue_date,due_date,amount,category,account_id,classification_status,classification_source,receipt_status,payment_method,invoice_ref,fingerprint,raw) VALUES($1,$2,$3,'FILES',$4,$5,$6,$7::date,$8::date,$9,$10,$11,$12,$13,'OPEN',$14,$15,$16,$17::jsonb) ON CONFLICT(company_id,fingerprint) DO NOTHING RETURNING id`,[cid,sourceFileId,tx.rows[0].id,row.party||null,row.document||null,row.description,row.issueDate,row.dueDate,Math.abs(n(row.amount)),category,account?.id||c.account_id||null,row.category?'CONFIRMED':c.status,row.category?'FILE_MODEL':c.source,row.paymentMethod||null,row.invoiceRef||null,fp,JSON.stringify(row.raw||{})])
  if(!r.rowCount)await pool!.query(`DELETE FROM transactions WHERE id=$1`,[tx.rows[0].id])
  return Boolean(r.rowCount)
}

async function insertClassifiedTransactions(cid:string,sourceFileId:string,parsed:any,docType:string,company:any){
  let count=0
  for(const original of parsed.transactions||[]){let t={...original},direction=t.direction==='SAIDA'?'SAIDA':'ENTRADA',amount=n(t.amount);if(docType==='CREDIT_CARD_INVOICE'){direction='SAIDA';amount=-Math.abs(amount)}
    const c=await classify({...t,direction,amount},cid,company)
    let category=c.category||'A classificar',role='BANK_MOVEMENT',cash=true,dre=category!=='Transferência entre contas próprias',financial=t.financialStatus||'PAID'
    if(docType==='CARD_MACHINE_STATEMENT'){role='SALES_EVENT';cash=false;dre=true;if(direction==='ENTRADA'&&(category==='A classificar'||!category))category='Receita de vendas'}
    if(docType==='CREDIT_CARD_INVOICE'){role='CARD_PURCHASE';cash=false;dre=true;financial='OPEN'}
    if(category==='Transferência entre contas próprias'){role='TRANSFER';dre=false;cash=true}
    const account=await ensureAccount(cid,category,direction as 'ENTRADA'|'SAIDA')
    await pool!.query(`INSERT INTO transactions(company_id,source_file_id,occurred_at,competence_at,due_at,paid_at,description,normalized_party,counterparty_document,direction,amount,gross_amount,fee_amount,net_amount,category,account_id,classification_confidence,classification_status,classification_source,payment_method,financial_status,dre_impact,cash_impact,accounting_role,external_id,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26::jsonb)`,[cid,sourceFileId,t.occurredAt||new Date(),t.competenceAt||t.occurredAt||new Date(),t.dueAt||null,t.paidAt||null,t.description||'Lançamento importado',c.normalized_party||null,c.counterparty_document||null,direction,amount,t.grossAmount??null,t.feeAmount??null,t.netAmount??null,category,account?.id||c.account_id||null,c.confidence,c.status,c.source,t.paymentMethod||null,financial,dre,cash,role,t.externalId||null,JSON.stringify({...t.raw,user_document_type:docType})])
    count++
  }
  return count
}

async function ensureDemo(){
  if(!pool)throw new Error('Banco não configurado')
  let company=await pool.query(`SELECT id,name FROM companies WHERE is_demo=true ORDER BY created_at LIMIT 1`)
  if(!company.rowCount)company=await pool.query(`INSERT INTO companies(name,document,sector,activity,active,is_demo) VALUES('Empresa Aurora Demo','00.000.000/0001-00','Comércio','Empresa fictícia para demonstração',true,true) RETURNING id,name`)
  const cid=company.rows[0].id;await ensureDefaultChart(cid)
  const email='demo@clara.local';let user=await pool.query(`SELECT id,email,name,role,status FROM users WHERE lower(email)=lower($1) LIMIT 1`,[email])
  if(!user.rowCount)user=await pool.query(`INSERT INTO users(email,name,password_hash,role,status) VALUES($1,'Administrador Demo',$2,'ADMIN','ACTIVE') RETURNING id,email,name,role,status`,[email,hashPassword(crypto.randomBytes(18).toString('hex'))])
  await pool.query(`INSERT INTO user_companies(user_id,company_id,role) VALUES($1,$2,'ADMIN') ON CONFLICT(user_id,company_id) DO UPDATE SET role='ADMIN'`,[user.rows[0].id,cid])
  const c=await pool.query(`SELECT count(*)::int n FROM transactions WHERE company_id=$1`,[cid]);if(n(c.rows[0]?.n)<20)await resetDemo(cid)
  return{companyId:cid,user:user.rows[0]}
}

async function resetDemo(cid:string){
  await pool!.query(`DELETE FROM receivables WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM payables WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM reconciliation_links WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM reconciliation_ignores WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM transactions WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM source_files WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM company_accounts WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM expected_sources WHERE company_id=$1`,[cid]);await pool!.query(`DELETE FROM pricing_models WHERE company_id=$1`,[cid]);
  await ensureDefaultChart(cid)
  await pool!.query(`INSERT INTO company_accounts(company_id,label,institution,agency,account) VALUES($1,'Conta principal','Banco Aurora','0001','12345-6'),($1,'Conta digital','Banco Horizonte','0001','98765-4')`,[cid])
  for(const [kind,label] of Object.entries(DOC_TYPES))await pool!.query(`INSERT INTO expected_sources(company_id,kind,label) VALUES($1,$2,$3) ON CONFLICT(company_id,kind) DO UPDATE SET label=excluded.label,active=true`,[cid,kind,label])
  const files:any={};for(const [kind,label] of Object.entries(DOC_TYPES)){const review=kind==='CREDIT_CARD_INVOICE';const f=await pool!.query(`INSERT INTO source_files(company_id,name,hash,kind,status,status_detail,record_count,confidence,validation_status,validation,period_start,period_end,import_scope) VALUES($1,$2,$3,$4,$5,$6,$7,96,$8,$9::jsonb,current_date-interval '12 months',current_date,'GENERAL') RETURNING id`,[cid,`${String(label).replace(/\s/g,'_')}_DEMO.xlsx`,crypto.createHash('sha256').update(`${cid}-${kind}`).digest('hex'),kind,review?'REVIEW':'IMPORTED',review?'Há 1 lançamento da fatura que precisa de conferência':'Arquivo fictício conferido',review?11:48,review?'MISMATCH':'OK',JSON.stringify(review?{error:'Total da fatura difere R$ 89,90 do total extraído',differences:{total:89.90}}:{status:'OK'})]);files[kind]=f.rows[0].id}
  const accounts=await pool!.query(`SELECT id,code,name FROM chart_accounts WHERE company_id=$1`,[cid]),byCode=new Map(accounts.rows.map((a:any)=>[a.code,a]))
  const today=new Date();for(let back=11;back>=0;back--){const d=new Date(today.getFullYear(),today.getMonth()-back,10),period=`${d.getFullYear()}-${pad(d.getMonth()+1)}`,factor=1+(11-back)*.025
    const rows=[
      ['05','Recebimento Cliente Horizonte','ENTRADA',8200*factor,'1.01','PIX','BANK_STATEMENT'],['12','Recebimento Loja Sol','ENTRADA',6150*factor,'1.01','Transferência','BANK_STATEMENT'],['18','Vendas maquineta Aurora','ENTRADA',5400*factor,'1.01','Cartão de crédito','CARD_MACHINE_STATEMENT'],
      ['06','Fornecedor Verde Vida','SAIDA',-4200*factor,'3.01','Boleto','BANK_STATEMENT'],['08','Google Ads','SAIDA',-1190*factor,'4.01','Cartão de crédito','CREDIT_CARD_INVOICE'],['15','Aluguel Comercial','SAIDA',-5200,'4.05','PIX','BANK_STATEMENT'],['20','CELESC','SAIDA',-780*factor,'4.03','Débito automático','BANK_STATEMENT'],['23','Sistemas Nuvem','SAIDA',-690*factor,'4.02','Cartão de crédito','CREDIT_CARD_INVOICE']]
    for(const [day,desc,dir,value,code,payment,source] of rows){const acc=byCode.get(code),date=`${period}-${day}`;await pool!.query(`INSERT INTO transactions(company_id,source_file_id,occurred_at,competence_at,description,normalized_party,direction,amount,category,account_id,classification_confidence,classification_status,classification_source,payment_method,financial_status,dre_impact,cash_impact,accounting_role,raw) VALUES($1,$2,$3::date,$3::date,$4,upper($4),$5,$6,$7,$8,100,'CONFIRMED','DEMO',$9,'PAID',true,$10,$11,$12::jsonb)`,[cid,files[source],date,desc,dir,value,acc?.name||'A classificar',acc?.id||null,payment,source!=='CREDIT_CARD_INVOICE',source==='CARD_MACHINE_STATEMENT'?'SALES_EVENT':source==='CREDIT_CARD_INVOICE'?'CARD_PURCHASE':'BANK_MOVEMENT',JSON.stringify({source:'demo',document_type:source,nsu:`DEMO-${period}-${day}`})])}
  }
  const company=await getCompany(cid);for(let i=1;i<=8;i++){const due=new Date(today.getTime()+i*7*86400000),issue=new Date(due.getTime()-25*86400000),row={party:`Fornecedor Demo ${i}`,description:i%2?'Compra de mercadoria':'Serviço recorrente',issueDate:dateOnly(issue),dueDate:dateOnly(due),amount:900+i*285,category:i%2?'Compra de mercadoria / insumos':'Serviços terceirizados',paymentMethod:i%2?'Boleto':'PIX',invoiceRef:`P-${1000+i}`,raw:{source:'demo'}};await insertPayable(cid,row,files.PAYABLES,company)}
  for(let i=1;i<=8;i++){const due=new Date(today.getTime()+i*6*86400000),issue=new Date(due.getTime()-20*86400000),row={party:`Cliente Demo ${i}`,description:'Venda a prazo',issueDate:dateOnly(issue),dueDate:dateOnly(due),amount:1400+i*360,category:'Receita de vendas',paymentMethod:i%2?'Boleto':'PIX',invoiceRef:`R-${2000+i}`,raw:{source:'demo'}};await insertReceivable(cid,row,files.RECEIVABLES,company)}
  await pool!.query(`INSERT INTO pricing_models(company_id,name,mode,lines,target_margin,markup) VALUES($1,'Modelo varejo','SALE',$2::jsonb,25,2)`,[cid,JSON.stringify([{id:'tax',name:'Impostos',basis:'SALE_PERCENT',value:8},{id:'card',name:'Taxa de cartão',basis:'SALE_PERCENT',value:2.5}])])
}

function startOfWeek(d:Date){const x=new Date(d);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);x.setHours(0,0,0,0);return x}
function addDays(d:Date,days:number){const x=new Date(d);x.setDate(x.getDate()+days);return x}
async function presentationData(cid:string,kind:string,query:any){const company=await getCompany(cid),today=query.reference?new Date(`${query.reference}T12:00:00`):new Date();if(kind==='weekly'){const current=startOfWeek(today),from=dateOnly(addDays(current,-7))!,to=dateOnly(addDays(current,-1))!,nextFrom=dateOnly(addDays(current,7))!,nextTo=dateOnly(addDays(current,13))!;const [tx,pay,rec]=await Promise.all([pool!.query(`SELECT description,amount,direction,category,competence_at FROM transactions WHERE company_id=$1 AND competence_at BETWEEN $2::date AND $3::date AND dre_impact=true ORDER BY abs(amount) DESC`,[cid,from,to]),pool!.query(`SELECT supplier,description,due_date,amount FROM payables WHERE company_id=$1 AND due_date BETWEEN $2::date AND $3::date AND payment_status<>'PAID' ORDER BY due_date,amount DESC`,[cid,nextFrom,nextTo]),pool!.query(`SELECT customer,description,due_date,amount FROM receivables WHERE company_id=$1 AND due_date BETWEEN $2::date AND $3::date AND receipt_status<>'RECEIVED' ORDER BY due_date,amount DESC`,[cid,nextFrom,nextTo])]);const inflow=tx.rows.filter((x:any)=>x.direction==='ENTRADA').reduce((a:any,x:any)=>a+n(x.amount),0),outflow=tx.rows.filter((x:any)=>x.direction==='SAIDA').reduce((a:any,x:any)=>a+Math.abs(n(x.amount)),0);return{company,kind,from,to,nextFrom,nextTo,inflow,outflow,result:inflow-outflow,transactions:tx.rows,payables:pay.rows,receivables:rec.rows}}
  const period=/^\d{4}-\d{2}$/.test(query.period||'')?query.period:`${today.getFullYear()}-${pad(today.getMonth()+1)}`,[y,m]=period.split('-').map(Number),from=`${period}-01`,to=`${period}-${pad(new Date(y,m,0).getDate())}`;const [tx,pay,rec]=await Promise.all([pool!.query(`SELECT description,amount,direction,category,competence_at FROM transactions WHERE company_id=$1 AND competence_at BETWEEN $2::date AND $3::date AND dre_impact=true ORDER BY abs(amount) DESC`,[cid,from,to]),pool!.query(`SELECT supplier,description,due_date,amount,payment_status FROM payables WHERE company_id=$1 AND due_date BETWEEN $2::date AND $3::date ORDER BY amount DESC`,[cid,from,to]),pool!.query(`SELECT customer,description,due_date,amount,receipt_status FROM receivables WHERE company_id=$1 AND due_date BETWEEN $2::date AND $3::date ORDER BY amount DESC`,[cid,from,to])]);const revenue=tx.rows.filter((x:any)=>x.direction==='ENTRADA').reduce((a:any,x:any)=>a+n(x.amount),0),expenses=tx.rows.filter((x:any)=>x.direction==='SAIDA').reduce((a:any,x:any)=>a+Math.abs(n(x.amount)),0);return{company,kind,period,from,to,inflow:revenue,outflow:expenses,result:revenue-expenses,transactions:tx.rows,payables:pay.rows,receivables:rec.rows}}

async function buildPdf(data:any){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),page=pdf.addPage([842,595]),{width,height}=page.getSize();let y=height-48;const blue=rgb(.05,.18,.34),gray=rgb(.35,.39,.45),light=rgb(.94,.96,.98),green=rgb(.1,.55,.34),red=rgb(.75,.2,.2)
  const text=(s:any,x:number,yy:number,size=10,f=font,color=gray)=>page.drawText(String(s??''),{x,y:yy,size,font:f,color,maxWidth:width-x-40})
  page.drawRectangle({x:0,y:height-110,width,height:110,color:blue});text('CLARA BPO FINANCEIRO',42,height-42,11,bold,rgb(1,1,1));text(data.kind==='weekly'?'Apresentação Semanal':'Apresentação Mensal',42,height-70,24,bold,rgb(1,1,1));text(data.company?.name||'Empresa',42,height-94,12,font,rgb(.85,.9,.96));y=height-145
  const cards=[['Entradas / Receita',data.inflow,green],['Saídas / Despesas',data.outflow,red],['Resultado',data.result,data.result>=0?green:red],['Próximos recebimentos',(data.receivables||[]).reduce((a:any,x:any)=>a+n(x.amount),0),blue]];cards.forEach((c:any,i:number)=>{const x=42+i*190;page.drawRectangle({x,y:y-58,width:170,height:58,color:light,borderColor:rgb(.85,.88,.92),borderWidth:1});text(c[0],x+10,y-20,8,bold,gray);text(money(c[1]),x+10,y-43,15,bold,c[2])});y-=90
  text(data.kind==='weekly'?`Semana analisada: ${data.from} a ${data.to} · Próxima semana: ${data.nextFrom} a ${data.nextTo}`:`Período: ${data.period}`,42,y,10,bold,blue);y-=24
  text('Leitura executiva',42,y,13,bold,blue);y-=18;const duePay=(data.payables||[]).reduce((a:any,x:any)=>a+n(x.amount),0),dueRec=(data.receivables||[]).reduce((a:any,x:any)=>a+n(x.amount),0),summary=data.result>=0?`O período encerrou positivo em ${money(data.result)}.`:`O período encerrou negativo em ${money(Math.abs(data.result))}.`;text(`${summary} Há ${money(duePay)} em pagamentos e ${money(dueRec)} em recebimentos no horizonte apresentado.`,42,y,10,font,gray);y-=42
  const max=Math.max(n(data.inflow),n(data.outflow),1),barW=280;text('Receita / Entradas',42,y,9,bold,gray);page.drawRectangle({x:145,y:y-2,width:barW*n(data.inflow)/max,height:12,color:green});text(money(data.inflow),440,y,9,bold,green);y-=25;text('Despesas / Saídas',42,y,9,bold,gray);page.drawRectangle({x:145,y:y-2,width:barW*n(data.outflow)/max,height:12,color:red});text(money(data.outflow),440,y,9,bold,red);y-=42
  const table=(title:string,rows:any[],partyKey:string)=>{text(title,42,y,12,bold,blue);y-=18;page.drawRectangle({x:42,y:y-18,width:758,height:20,color:light});text('Data',50,y-5,8,bold);text('Descrição',120,y-5,8,bold);text('Parte',430,y-5,8,bold);text('Valor',690,y-5,8,bold);y-=24;for(const r of rows.slice(0,7)){text(dateOnly(r.due_date||r.competence_at)||'—',50,y,8);text(String(r.description||'').slice(0,50),120,y,8);text(String(r[partyKey]||r.category||'').slice(0,28),430,y,8);text(money(Math.abs(n(r.amount))),690,y,8,bold);y-=18}y-=18}
  table(data.kind==='weekly'?'Principais movimentos da semana':'Principais movimentos do mês',data.transactions||[],'category');if(y<160){/* mantém o PDF executivo em uma página quando possível */}table('Contas a pagar',data.payables||[],'supplier');
  const page2=pdf.addPage([842,595]),t2=(s:any,x:number,yy:number,size=10,f=font,color=gray)=>page2.drawText(String(s??''),{x,y:yy,size,font:f,color,maxWidth:width-x-40});page2.drawRectangle({x:0,y:height-80,width,height:80,color:blue});t2('Próximos recebimentos e pontos de atenção',42,height-50,20,bold,rgb(1,1,1));let y2=height-115;t2('Contas a receber',42,y2,13,bold,blue);y2-=24;for(const r of (data.receivables||[]).slice(0,14)){page2.drawLine({start:{x:42,y:y2-5},end:{x:800,y:y2-5},thickness:.5,color:rgb(.88,.9,.92)});t2(dateOnly(r.due_date)||'—',50,y2,8);t2(String(r.customer||r.description||'').slice(0,42),125,y2,9,bold);t2(String(r.description||'').slice(0,52),390,y2,8);t2(money(r.amount),700,y2,9,bold,green);y2-=25}y2-=15;t2('O que merece atenção',42,y2,13,bold,blue);y2-=24;const attention=[data.result<0?'Resultado do período está negativo.':'Resultado do período está positivo.',duePay>dueRec?'Pagamentos futuros superam os recebimentos futuros no horizonte.':'Recebimentos futuros cobrem os pagamentos apresentados.',(data.payables||[]).length?`${data.payables.length} compromisso(s) financeiro(s) aparecem no horizonte.`:'Nenhum compromisso relevante encontrado no horizonte.'];attention.forEach((a,i)=>{t2(`• ${a}`,55,y2-i*23,10,font,gray)})
  return Buffer.from(await pdf.save())}

export function registerV070Routes(app:any){
  app.post('/api/import-classified',collectUploads,async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const type=String(req.query?.type||'').toUpperCase();if(!DOC_TYPES[type])return res.status(400).json({message:'Informe o tipo do arquivo.'});if(!req.uploadedFiles?.length)return res.status(400).json({message:'Nenhum arquivo recebido.'});const cid=req.companyId,company=await getCompany(cid),results:any[]=[];for(const f of req.uploadedFiles){const hash=crypto.createHash('sha256').update(f.buffer).digest('hex');let sourceFileId:string|null=null;try{const exists=await pool.query(`SELECT id FROM source_files WHERE company_id=$1 AND hash=$2 LIMIT 1`,[cid,hash]);if(exists.rowCount){results.push({name:f.originalname,status:'DUPLICATE',detail:'Arquivo já importado.'});continue}const ext=path.extname(f.originalname).toLowerCase();if(['PAYABLES','RECEIVABLES'].includes(type)&&!['.xlsx','.xls','.csv'].includes(ext))throw new Error(`${DOC_TYPES[type]} deve ser importado pelo modelo Excel/CSV da Clara.`);let recordCount=0,status='IMPORTED',detail='Arquivo lido e processado',validation='OK';const sf=await pool.query(`INSERT INTO source_files(company_id,name,hash,kind,status,status_detail,record_count,confidence,validation_status,validation,content,mime_type,import_scope) VALUES($1,$2,$3,$4,'IMPORTED','Processando...',0,90,'OK','{}'::jsonb,$5,$6,'GENERAL') RETURNING id`,[cid,f.originalname,hash,type,f.buffer,f.mimetype]);sourceFileId=sf.rows[0].id;if(type==='PAYABLES'||type==='RECEIVABLES'){const rows=parseModelSpreadsheet(f.buffer,type);if(!rows.length){status='REVIEW';validation='ERROR';detail='O arquivo não segue o modelo esperado ou não possui vencimento/valor.'}else for(const row of rows)recordCount+=(type==='PAYABLES'?await insertPayable(cid,row,sf.rows[0].id,company):await insertReceivable(cid,row,sf.rows[0].id,company))?1:0}else{const parsed=ext==='.pdf'?await parsePdf(f.buffer):parseTabular(f.buffer);recordCount=await insertClassifiedTransactions(cid,sf.rows[0].id,parsed,type,company);if(!recordCount){status='REVIEW';validation='ERROR';detail='O tipo foi confirmado pelo usuário, mas nenhum lançamento pôde ser extraído. Clique no alerta para revisar.'}}
      await pool.query(`UPDATE source_files SET status=$3,status_detail=$4,record_count=$5,validation_status=$6,validation=$7::jsonb,processed_at=now() WHERE id=$1 AND company_id=$2`,[sf.rows[0].id,cid,status,detail,recordCount,validation,JSON.stringify(validation==='ERROR'?{error:detail}:{status:'OK',confirmedType:type})]);await pool.query(`INSERT INTO expected_sources(company_id,kind,label) VALUES($1,$2,$3) ON CONFLICT(company_id,kind) DO UPDATE SET label=excluded.label,active=true`,[cid,type,DOC_TYPES[type]]);results.push({name:f.originalname,status,kind:type,records:recordCount,detail})}catch(e:any){const errorDetail=e?.message||String(e);if(sourceFileId)await pool.query(`UPDATE source_files SET status='REVIEW',status_detail=$3,validation_status='ERROR',validation=$4::jsonb,processed_at=now() WHERE id=$1 AND company_id=$2`,[sourceFileId,cid,errorDetail,JSON.stringify({error:errorDetail})]).catch(()=>{});results.push({name:f.originalname,status:'ERROR',detail:errorDetail})}}
    res.json({message:`${results.filter(x=>x.status==='IMPORTED').length} arquivo(s) processado(s).`,results})})

  app.get('/api/receivables',async(req:any,res:any)=>{if(!pool)return res.json({rows:[],summary:{},byCustomer:[],byCategory:[]});const from=String(req.query.from||new Date().toISOString().slice(0,10)),to=String(req.query.to||new Date(Date.now()+120*86400000).toISOString().slice(0,10)),r=await pool.query(`SELECT r.*,a.code account_code,a.name account_name,sf.name source_file_name,t.financial_status transaction_financial_status FROM receivables r LEFT JOIN chart_accounts a ON a.id=r.account_id LEFT JOIN source_files sf ON sf.id=r.source_file_id LEFT JOIN transactions t ON t.id=r.transaction_id WHERE r.company_id=$1 AND r.due_date BETWEEN $2::date AND $3::date ORDER BY r.due_date,r.customer,r.id`,[req.companyId,from,to]),today=new Date().toISOString().slice(0,10);for(const row of r.rows){if(row.transaction_financial_status==='PAID')row.receipt_status='RECEIVED';else if(row.receipt_status==='OPEN'&&String(row.due_date).slice(0,10)<today)row.receipt_status='OVERDUE'}const open=r.rows.filter((x:any)=>x.receipt_status!=='RECEIVED'),total=open.reduce((a:any,x:any)=>a+n(x.amount)-n(x.received_amount),0),overdue=open.filter((x:any)=>String(x.due_date).slice(0,10)<today).reduce((a:any,x:any)=>a+n(x.amount)-n(x.received_amount),0),by=(key:string)=>{const m=new Map<string,number>();for(const x of open){const k=String(x[key]||'Não informado');m.set(k,(m.get(k)||0)+n(x.amount)-n(x.received_amount))}return[...m].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)};res.json({rows:r.rows,summary:{total,overdue,count:open.length},byCustomer:by('customer'),byCategory:by('category')})})
  app.post('/api/receivables',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const {customer='',customerDocument='',description,dueDate,issueDate,amount,category='Receita de vendas',accountId=null,paymentMethod='',invoiceRef=''}=req.body||{};if(!description||!dueDate||!n(amount))return res.status(400).json({message:'Informe descrição, vencimento e valor.'});const company=await getCompany(req.companyId),ok=await insertReceivable(req.companyId,{party:customer,document:customerDocument,description,issueDate:issueDate||dueDate,dueDate,amount:n(amount),category,accountId,paymentMethod,invoiceRef,raw:{source:'manual'}},null,company);if(!ok)return res.status(409).json({message:'Este título já existe.'});res.json({ok:true})})
  app.patch('/api/receivables/:id',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const cur=await pool.query(`SELECT * FROM receivables WHERE id=$1 AND company_id=$2 LIMIT 1`,[req.params.id,req.companyId]);if(!cur.rowCount)return res.status(404).json({message:'Conta a receber não encontrada.'});const before=cur.rows[0],received=req.body.receivedAmount===undefined?n(before.received_amount):n(req.body.receivedAmount),status=req.body.receiptStatus||(received>=n(req.body.amount||before.amount)?'RECEIVED':received>0?'PARTIAL':before.receipt_status),accountId=req.body.accountId===undefined?before.account_id:(req.body.accountId||null),account=accountId?await findAccountByName(req.companyId,req.body.category||before.category):null,category=req.body.category||account?.name||before.category;const r=await pool.query(`UPDATE receivables SET customer=COALESCE($3,customer),description=COALESCE($4,description),due_date=COALESCE($5::date,due_date),amount=COALESCE($6,amount),category=COALESCE($7,category),account_id=$8,receipt_status=$9,received_amount=$10,received_at=CASE WHEN $9='RECEIVED' THEN COALESCE(received_at,now()) ELSE received_at END,updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING *`,[req.params.id,req.companyId,req.body.customer??null,req.body.description??null,req.body.dueDate??null,req.body.amount??null,category,accountId,status,received]);if(before.transaction_id)await pool.query(`UPDATE transactions SET financial_status=CASE WHEN $3='RECEIVED' THEN 'PAID' ELSE financial_status END,paid_at=CASE WHEN $3='RECEIVED' THEN COALESCE(paid_at,now()) ELSE paid_at END,category=COALESCE($4,category),account_id=$5 WHERE id=$1 AND company_id=$2`,[before.transaction_id,req.companyId,status,category,accountId]);res.json(r.rows[0])})
  app.delete('/api/receivables/:id',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const r=await pool.query(`DELETE FROM receivables WHERE id=$1 AND company_id=$2 RETURNING transaction_id`,[req.params.id,req.companyId]);if(!r.rowCount)return res.status(404).json({message:'Conta a receber não encontrada.'});if(r.rows[0].transaction_id)await pool.query(`DELETE FROM transactions WHERE id=$1 AND company_id=$2 AND raw->>'source'='receivables_v070'`,[r.rows[0].transaction_id,req.companyId]);res.json({ok:true})})
  app.get('/api/receivables/template',async(_req:any,res:any)=>{const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet([['cliente','cnpj_cpf','descricao','data_emissao','vencimento','valor','categoria','forma_pagamento','numero_documento'],['Cliente Exemplo','12.345.678/0001-90','Venda a prazo','01/09/2026','15/09/2026',2450.50,'Receita de vendas','Boleto','NF-4321']]);XLSX.utils.book_append_sheet(wb,ws,'Contas a Receber');const buffer=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.header('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').header('Content-Disposition','attachment; filename="modelo-contas-a-receber-clara.xlsx"').send(buffer)})

  app.get('/api/reconciliation/transaction/:id',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const r=await pool.query(`SELECT t.*,sf.name source_file_name,sf.kind source_kind,sf.status source_status FROM transactions t LEFT JOIN source_files sf ON sf.id=t.source_file_id WHERE t.id=$1 AND t.company_id=$2 LIMIT 1`,[req.params.id,req.companyId]);if(!r.rowCount)return res.status(404).json({message:'Movimentação não encontrada.'});const p=await pool.query(`SELECT id,supplier party,description,due_date,amount,payment_status status,'PAYABLE' kind FROM payables WHERE company_id=$1 AND abs(amount-abs($2::numeric))<=0.05 AND abs(due_date-$3::date)<=15 UNION ALL SELECT id,customer party,description,due_date,amount,receipt_status status,'RECEIVABLE' kind FROM receivables WHERE company_id=$1 AND abs(amount-abs($2::numeric))<=0.05 AND abs(due_date-$3::date)<=15 ORDER BY due_date LIMIT 12`,[req.companyId,n(r.rows[0].amount),dateOnly(r.rows[0].competence_at||r.rows[0].occurred_at)]);res.json({transaction:r.rows[0],candidates:p.rows})})

  app.get('/api/presentations/:kind/pdf',async(req:any,res:any)=>{const kind=String(req.params.kind||'').toLowerCase();if(!['weekly','monthly'].includes(kind))return res.status(404).json({message:'Tipo de apresentação inválido.'});const data=await presentationData(req.companyId,kind,req.query||{}),buffer=await buildPdf(data),filename=kind==='weekly'?'clara-apresentacao-semanal.pdf':'clara-apresentacao-mensal.pdf';res.header('Content-Type','application/pdf').header('Content-Disposition',`attachment; filename="${filename}"`).send(buffer)})

  app.get('/api/demo/session',async(_req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const demo=await ensureDemo(),session=await createSession(demo.user.id),payload=await authPayload(demo.user);res.json({token:session.token,expiresAt:session.expiresAt,...payload})})
  app.post('/api/demo/reset',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const c=await pool.query(`SELECT is_demo FROM companies WHERE id=$1 LIMIT 1`,[req.companyId]);if(!c.rows[0]?.is_demo)return res.status(403).json({message:'A restauração só existe no ambiente de demonstração.'});await resetDemo(req.companyId);res.json({ok:true,message:'Dados fictícios restaurados.'})})
}
