import {pool,findAccountByName} from './db.js'

const n=(v:any)=>Number(v||0)
const pad=(v:any)=>String(v).padStart(2,'0')
const iso=(v:any)=>{if(!v)return null;if(v instanceof Date&&!Number.isNaN(v.getTime()))return`${v.getFullYear()}-${pad(v.getMonth()+1)}-${pad(v.getDate())}`;const s=String(v),m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:null}

export function registerV080ExtraRoutes(app:any){
  app.post('/api/payables-v080-update',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const b=req.body||{},id=String(b.id||'');const cur=await pool.query(`SELECT * FROM payables WHERE id=$1 AND company_id=$2 LIMIT 1`,[id,req.companyId]);if(!cur.rowCount)return res.status(404).json({message:'Conta a pagar não encontrada.'});const p=cur.rows[0],accountId=b.accountId===undefined?p.account_id:(b.accountId||null),account=accountId?await pool.query(`SELECT id,name FROM chart_accounts WHERE id=$1 AND company_id=$2 LIMIT 1`,[accountId,req.companyId]):null,category=b.category||account?.rows?.[0]?.name||p.category,amount=b.amount===undefined?n(p.amount):Math.abs(n(b.amount)),competence=b.competenceDate||iso(p.competence_date)||iso(p.issue_date)||iso(p.due_date),due=b.dueDate===undefined?iso(p.due_date):(b.dueDate||null),status=b.paymentStatus||p.payment_status,paidAmount=status==='PAID'?amount:(b.paidAmount===undefined?n(p.paid_amount):n(b.paidAmount));const r=await pool.query(`UPDATE payables SET supplier=COALESCE($3,supplier),description=COALESCE($4,description),competence_date=$5::date,due_date=$6::date,amount=$7,category=$8,account_id=$9,payment_status=$10,paid_amount=$11,paid_at=CASE WHEN $10='PAID' THEN COALESCE(paid_at,now()) ELSE paid_at END,updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING *`,[id,req.companyId,b.supplier??null,b.description??null,competence,due,amount,category,accountId,status,paidAmount]);if(p.transaction_id)await pool.query(`UPDATE transactions SET competence_at=$3::date,due_at=$4::date,amount=-abs($5),category=$6,account_id=$7,financial_status=CASE WHEN $8='PAID' THEN 'PAID' ELSE financial_status END,paid_at=CASE WHEN $8='PAID' THEN COALESCE(paid_at,now()) ELSE paid_at END WHERE id=$1 AND company_id=$2`,[p.transaction_id,req.companyId,competence,due,amount,category,accountId,status]);res.json(r.rows[0])})

  app.get('/api/receivables-v080',async(req:any,res:any)=>{if(!pool)return res.json({rows:[],summary:{}});const period=/^\d{4}-\d{2}$/.test(String(req.query?.period||''))?String(req.query.period):new Date().toISOString().slice(0,7),[y,m]=period.split('-').map(Number),from=`${period}-01`,to=`${period}-${pad(new Date(y,m,0).getDate())}`,r=await pool.query(`SELECT r.*,sf.name source_file_name FROM receivables r LEFT JOIN source_files sf ON sf.id=r.source_file_id WHERE r.company_id=$1 AND (r.competence_date BETWEEN $2::date AND $3::date OR (r.receipt_status<>'RECEIVED' AND r.due_date IS NULL)) ORDER BY r.receipt_status='RECEIVED',r.due_date NULLS FIRST,r.issue_date`,[req.companyId,from,to]),today=new Date().toISOString().slice(0,10);for(const row of r.rows)if(row.receipt_status==='OPEN'&&row.due_date&&iso(row.due_date)!<today)row.receipt_status='OVERDUE';const open=r.rows.filter((x:any)=>x.receipt_status!=='RECEIVED'),total=open.reduce((a:number,x:any)=>a+n(x.amount)-n(x.received_amount),0),undated=open.filter((x:any)=>!x.due_date).reduce((a:number,x:any)=>a+n(x.amount)-n(x.received_amount),0),overdue=open.filter((x:any)=>x.due_date&&iso(x.due_date)!<today).reduce((a:number,x:any)=>a+n(x.amount)-n(x.received_amount),0);res.json({period,rows:r.rows,summary:{total,undated,overdue,count:open.length}})})

  app.post('/api/receivables-v080-update',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const b=req.body||{},id=String(b.id||''),cur=await pool.query(`SELECT * FROM receivables WHERE id=$1 AND company_id=$2 LIMIT 1`,[id,req.companyId]);if(!cur.rowCount)return res.status(404).json({message:'Conta a receber não encontrada.'});const p=cur.rows[0],amount=b.amount===undefined?n(p.amount):Math.abs(n(b.amount)),due=b.dueDate===undefined?iso(p.due_date):(b.dueDate||null),status=b.receiptStatus||p.receipt_status,received=status==='RECEIVED'?amount:(b.receivedAmount===undefined?n(p.received_amount):n(b.receivedAmount)),r=await pool.query(`UPDATE receivables SET customer=COALESCE($3,customer),description=COALESCE($4,description),due_date=$5::date,amount=$6,receipt_status=$7,received_amount=$8,received_at=CASE WHEN $7='RECEIVED' THEN COALESCE(received_at,now()) ELSE received_at END,updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING *`,[id,req.companyId,b.customer??null,b.description??null,due,amount,status,received]);if(p.transaction_id)await pool.query(`UPDATE transactions SET due_at=$3::date,amount=abs($4),financial_status=CASE WHEN $5='RECEIVED' THEN 'PAID' ELSE financial_status END,paid_at=CASE WHEN $5='RECEIVED' THEN COALESCE(paid_at,now()) ELSE paid_at END WHERE id=$1 AND company_id=$2`,[p.transaction_id,req.companyId,due,amount,status]);res.json(r.rows[0])})
}
