import crypto from 'node:crypto'
import path from 'node:path'
import * as XLSX from 'xlsx'
import {pool,getCompany,findAccountByName} from './db.js'
import {parsePdf} from './parsers/pdf.js'
import {parseTabular} from './parsers/tabular.js'
import {classify} from './services/classify.js'
import {adaptUnknownPdf} from './services/ai.js'

const n=(v:any)=>Number(v||0)
const pad=(v:any)=>String(v).padStart(2,'0')
const clean=(v:any)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'')
const iso=(v:any)=>{if(!v)return null;if(v instanceof Date&&!Number.isNaN(v.getTime()))return`${v.getFullYear()}-${pad(v.getMonth()+1)}-${pad(v.getDate())}`;const s=String(v).trim(),br=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/),us=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(br)return`${br[3]}-${pad(br[2])}-${pad(br[1])}`;return us?`${us[1]}-${us[2]}-${us[3]}`:null}
const amount=(v:any)=>{if(typeof v==='number')return Math.abs(v);const s=String(v??'').replace(/R\$\s?/gi,'').replace(/\s/g,'');const x=s.includes(',')?s.replace(/\./g,'').replace(',','.'):s;return Math.abs(Number(x.replace(/[^0-9.-]/g,''))||0)}
const hash=(...parts:any[])=>crypto.createHash('sha256').update(parts.map(x=>String(x??'')).join('|')).digest('hex')
const addMonths=(date:string,months:number)=>{const[y,m,d]=date.split('-').map(Number),x=new Date(y,m-1+months,Math.min(d,28));return`${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`}
const dayDiff=(a:any,b:any)=>Math.abs((new Date(`${iso(a)}T12:00:00`).getTime()-new Date(`${iso(b)}T12:00:00`).getTime())/86400000)
const TYPES:any={BANK_STATEMENT:'Extrato Bancário',CARD_MACHINE_STATEMENT:'Extrato Maquineta Cartão',CREDIT_CARD_INVOICE:'Fatura Cartão de Crédito',SALES_REPORT:'Relatório de Vendas / Caixa',PAYABLES:'Contas a Pagar',RECEIVABLES:'Contas a Receber'}

async function collectUploads(req:any){const files:any[]=[];for await(const part of req.files())files.push({buffer:await part.toBuffer(),originalname:part.filename||'arquivo',mimetype:part.mimetype||'application/octet-stream'});req.uploadedFiles=files}
async function accountFor(cid:string,name:string,direction:'ENTRADA'|'SAIDA'){
  if(!name||name==='A classificar')return null
  const found=await findAccountByName(cid,name);if(found)return found
  const revenue=direction==='ENTRADA',section=revenue?'RECEITA_BRUTA':'DESPESAS_OPERACIONAIS',type=revenue?'REVENUE':'EXPENSE',parentName=revenue?'Receitas':'Despesas operacionais'
  const parent=await pool!.query(`SELECT id FROM chart_accounts WHERE company_id=$1 AND active=true AND is_group=true AND upper(name)=upper($2) LIMIT 1`,[cid,parentName]),ord=await pool!.query(`SELECT COALESCE(max(dre_order),100)::int m FROM chart_accounts WHERE company_id=$1`,[cid])
  const r=await pool!.query(`INSERT INTO chart_accounts(company_id,name,parent_id,account_type,dre_section,dre_order,is_group,active) VALUES($1,$2,$3,$4,$5,$6,false,true) RETURNING id,name`,[cid,name,parent.rows[0]?.id||null,type,section,n(ord.rows[0]?.m)+1]);return r.rows[0]
}
async function tx(cid:string,row:any){const r=await pool!.query(`INSERT INTO transactions(company_id,source_file_id,occurred_at,competence_at,due_at,paid_at,description,normalized_party,counterparty_document,direction,amount,gross_amount,fee_amount,net_amount,category,account_id,classification_confidence,classification_status,classification_source,payment_method,financial_status,dre_impact,cash_impact,accounting_role,economic_key,external_id,raw) VALUES($1,$2,$3::date,$4::date,$5::date,$6::timestamptz,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27::jsonb) RETURNING id`,[cid,row.sourceFileId||null,row.occurredAt||row.competenceAt,row.competenceAt||row.occurredAt,row.dueAt||null,row.paidAt||null,row.description,row.normalizedParty||null,row.document||null,row.direction,row.amount,row.grossAmount??null,row.feeAmount??null,row.netAmount??null,row.category||'A classificar',row.accountId||null,row.confidence??100,row.classificationStatus||'CONFIRMED',row.classificationSource||'V080',row.paymentMethod||null,row.financialStatus||'OPEN',Boolean(row.dreImpact),Boolean(row.cashImpact),row.role||'ECONOMIC',row.economicKey||null,row.externalId||null,JSON.stringify(row.raw||{})]);return r.rows[0].id}

function parseModel(buffer:Buffer,kind:'PAYABLES'|'RECEIVABLES'){
  const wb=XLSX.read(buffer,{type:'buffer',cellDates:true}),out:any[]=[]
  const common:any={description:['DESCRICAO','HISTORICO','TITULO'],issue:['DATA_EMISSAO','EMISSAO','DATA'],competence:['COMPETENCIA','DATA_COMPETENCIA','DT_COMPETENCIA'],due:['VENCIMENTO','DATA_VENCIMENTO','DT_VENCIMENTO'],amount:['VALOR','VALOR_TITULO','VLR','TOTAL'],category:['CATEGORIA','CLASSIFICACAO','PLANO_DE_CONTAS','CONTA'],payment:['FORMA_PAGAMENTO','MEIO_PAGAMENTO'],invoice:['NUMERO','NUMERO_DOCUMENTO','NF','NOTA_FISCAL','CODIGO'],document:['CNPJ','CPF','DOCUMENTO','CPF_CNPJ']},party=kind==='PAYABLES'?['FORNECEDOR','FAVORECIDO','BENEFICIARIO','RAZAO_SOCIAL','NOME']:['CLIENTE','PAGADOR','SACADO','RAZAO_SOCIAL','NOME']
  for(const sheet of wb.SheetNames){const rows:any[]=XLSX.utils.sheet_to_json(wb.Sheets[sheet],{defval:''});if(!rows.length)continue;const headers=Object.keys(rows[0]),find=(aliases:string[])=>headers.find(h=>aliases.includes(clean(h))),c:any={};for(const k of Object.keys(common))c[k]=find(common[k]);c.party=find(party);if(!c.amount)continue
    for(const r of rows){const value=amount(r[c.amount]),issue=iso(r[c.issue]),competence=iso(r[c.competence])||issue,due=iso(r[c.due]);if(!value)continue;out.push({party:String(r[c.party]||'').trim(),document:String(r[c.document]||'').trim(),description:String(r[c.description]||r[c.party]||(kind==='PAYABLES'?'Conta a pagar':'Conta a receber')).trim(),issueDate:issue||competence||due,competenceDate:competence||due,dueDate:due,amount:value,category:String(r[c.category]||'').trim()||null,paymentMethod:String(r[c.payment]||'').trim()||null,invoiceRef:String(r[c.invoice]||'').trim()||null,raw:{sheet,row:r}})}
  }return out
}
function parseSales(buffer:Buffer){
  const wb=XLSX.read(buffer,{type:'buffer',cellDates:true}),out:any[]=[]
  const aliases:any={date:['DATA','DATA_VENDA','DT_VENDA','EMISSAO'],customer:['CLIENTE','NOME_CLIENTE','PAGADOR','NOME'],amount:['VALOR','VALOR_VENDA','TOTAL','VALOR_TOTAL'],payment:['FORMA_PAGAMENTO','PAGAMENTO','MEIO_PAGAMENTO','FORMA_RECEBIMENTO'],due:['VENCIMENTO','DATA_VENCIMENTO'],description:['DESCRICAO','PRODUTO','HISTORICO','VENDA'],pix:['PIX','VALOR_PIX'],card:['CARTAO','CARTAO_CREDITO','VALOR_CARTAO'],cash:['DINHEIRO','VALOR_DINHEIRO']}
  for(const sheet of wb.SheetNames){const rows:any[]=XLSX.utils.sheet_to_json(wb.Sheets[sheet],{defval:''});if(!rows.length)continue;const headers=Object.keys(rows[0]),find=(a:string[])=>headers.find(h=>a.includes(clean(h))),c:any={};for(const k of Object.keys(aliases))c[k]=find(aliases[k]);if(!c.date||!c.amount)continue
    for(const r of rows){const date=iso(r[c.date]),value=amount(r[c.amount]);if(!date||!value)continue;const splits:any[]=[];for(const[k,label]of[['pix','PIX'],['card','Cartão'],['cash','Dinheiro']] as any[]){const v=c[k]?amount(r[c[k]]):0;if(v)splits.push({method:label,amount:v})}const method=String(r[c.payment]||'').trim();out.push({date,customer:String(r[c.customer]||'').trim(),description:String(r[c.description]||'Venda').trim(),amount:value,paymentMethod:method,dueDate:iso(r[c.due]),splits,raw:{sheet,row:r}})}
  }return out
}
function installmentInfo(desc:string){const m=String(desc||'').match(/(?:PARC(?:ELA)?\s*)?(\d{1,2})\s*\/\s*(\d{1,2})/i)||String(desc||'').match(/(\d{1,2})\s+DE\s+(\d{1,2})/i);return m?{current:Number(m[1]),total:Number(m[2]),base:String(desc).replace(m[0],'').replace(/\s+/g,' ').trim()}:{current:1,total:1,base:String(desc||'').trim()}}

async function insertReceivableControl(cid:string,row:any,sourceFileId:string|null){const value=Math.abs(n(row.amount));if(!value)return null;const fp=hash(cid,'REC',row.saleKey||'',row.customer||'',row.paymentMethod||'',row.dueDate||'',value.toFixed(2),row.index||0),existing=await pool!.query(`SELECT id,transaction_id FROM receivables WHERE company_id=$1 AND fingerprint=$2 LIMIT 1`,[cid,fp]);if(existing.rowCount)return existing.rows[0]
  const t=await tx(cid,{sourceFileId,occurredAt:row.issueDate||row.competenceDate,competenceAt:row.competenceDate||row.issueDate,dueAt:row.dueDate,description:row.description||`Recebimento ${row.customer||''}`,normalizedParty:String(row.customer||'').toUpperCase()||null,document:row.document,direction:'ENTRADA',amount:value,category:row.category||'Receita de vendas',paymentMethod:row.paymentMethod,financialStatus:'OPEN',dreImpact:false,cashImpact:false,role:'RECEIVABLE_CONTROL',economicKey:row.saleKey,raw:{source:'v080_receivable_control',...row.raw}})
  const r=await pool!.query(`INSERT INTO receivables(company_id,source_file_id,transaction_id,origin_type,customer,customer_document,description,issue_date,competence_date,due_date,amount,category,account_id,classification_status,classification_source,receipt_status,payment_method,invoice_ref,fingerprint,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8::date,$9::date,$10::date,$11,$12,$13,'CONFIRMED','V080','OPEN',$14,$15,$16,$17::jsonb) ON CONFLICT(company_id,fingerprint) DO NOTHING RETURNING id,transaction_id`,[cid,sourceFileId,t,row.originType||'SALES_REPORT',row.customer||null,row.document||null,row.description||'Conta a receber',row.issueDate||row.competenceDate,row.competenceDate||row.issueDate,row.dueDate||null,value,row.category||'Receita de vendas',row.accountId||null,row.paymentMethod||null,row.invoiceRef||null,fp,JSON.stringify(row.raw||{})]);if(!r.rowCount)await pool!.query(`DELETE FROM transactions WHERE id=$1`,[t]);return r.rows[0]||null}
async function insertPayableEconomic(cid:string,row:any,sourceFileId:string|null,company:any){const value=Math.abs(n(row.amount)),competence=row.competenceDate||row.issueDate||row.dueDate,due=row.dueDate;if(!value||!competence)return null;const fake={description:row.description||row.party||'Conta a pagar',amount:-value,direction:'SAIDA'},c=await classify(fake,cid,company),category=row.category||c.category||'A classificar',acc=await accountFor(cid,category,'SAIDA'),fp=hash(cid,'PAY',row.originType||'',row.party||'',row.description||'',competence,due||'',value.toFixed(2),row.invoiceRef||'');const exists=await pool!.query(`SELECT id,transaction_id FROM payables WHERE company_id=$1 AND fingerprint=$2 LIMIT 1`,[cid,fp]);if(exists.rowCount)return exists.rows[0]
  const t=await tx(cid,{sourceFileId,occurredAt:row.issueDate||competence,competenceAt:competence,dueAt:due,description:row.description||row.party||'Conta a pagar',normalizedParty:c.normalized_party,document:row.document||c.counterparty_document,direction:'SAIDA',amount:-value,category,accountId:acc?.id||c.account_id,confidence:row.category?100:c.confidence,classificationStatus:row.category?'CONFIRMED':c.status,classificationSource:row.category?'V080':c.source,paymentMethod:row.paymentMethod,financialStatus:'OPEN',dreImpact:true,cashImpact:false,role:'PAYABLE_ECONOMIC',raw:{source:'v080_payable',...row.raw}})
  const r=await pool!.query(`INSERT INTO payables(company_id,source_file_id,transaction_id,origin_type,supplier,supplier_document,description,issue_date,competence_date,due_date,amount,category,account_id,classification_status,classification_source,payment_status,payment_method,invoice_ref,fingerprint,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8::date,$9::date,$10::date,$11,$12,$13,$14,$15,'OPEN',$16,$17,$18,$19::jsonb) ON CONFLICT(company_id,fingerprint) DO NOTHING RETURNING id,transaction_id`,[cid,sourceFileId,t,row.originType||'MANUAL',row.party||null,row.document||null,row.description||row.party||'Conta a pagar',row.issueDate||competence,competence,due||competence,value,category,acc?.id||c.account_id,row.category?'CONFIRMED':c.status,row.category?'V080':c.source,row.paymentMethod||null,row.invoiceRef||null,fp,JSON.stringify(row.raw||{})]);if(!r.rowCount)await pool!.query(`DELETE FROM transactions WHERE id=$1`,[t]);return r.rows[0]||null}
async function insertPayableControl(cid:string,row:any,sourceFileId:string|null){const value=Math.abs(n(row.amount));if(!value||!row.dueDate)return null;const fp=hash(cid,'CARD_PAY',row.economicKey,row.installment,row.dueDate,value.toFixed(2)),exists=await pool!.query(`SELECT id FROM payables WHERE company_id=$1 AND fingerprint=$2 LIMIT 1`,[cid,fp]);if(exists.rowCount)return exists.rows[0]
  const t=await tx(cid,{sourceFileId,occurredAt:row.competenceDate,competenceAt:row.competenceDate,dueAt:row.dueDate,description:row.description,direction:'SAIDA',amount:-value,category:'Liquidação de cartão de crédito',paymentMethod:'Cartão de crédito',financialStatus:'OPEN',dreImpact:false,cashImpact:false,role:'PAYABLE_CONTROL',economicKey:row.economicKey,raw:{source:'v080_card_installment',installment:row.installment,totalInstallments:row.totalInstallments}})
  const r=await pool!.query(`INSERT INTO payables(company_id,source_file_id,transaction_id,origin_type,supplier,description,issue_date,competence_date,due_date,amount,category,classification_status,classification_source,payment_status,payment_method,invoice_ref,fingerprint,raw) VALUES($1,$2,$3,'CREDIT_CARD_INSTALLMENT',$4,$5,$6::date,$6::date,$7::date,$8,'Liquidação de cartão de crédito','CONFIRMED','V080','OPEN','Cartão de crédito',$9,$10,$11::jsonb) ON CONFLICT(company_id,fingerprint) DO NOTHING RETURNING id`,[cid,sourceFileId,t,row.supplier||'Cartão de crédito',row.description,row.competenceDate,row.dueDate,value,row.invoiceRef||null,fp,JSON.stringify({installment:row.installment,totalInstallments:row.totalInstallments,economicKey:row.economicKey})]);if(!r.rowCount)await pool!.query(`DELETE FROM transactions WHERE id=$1`,[t]);return r.rows[0]||null}

function closingInfo(parsed:any,name:string){const validation={...(parsed?.validation||{})},text=String(parsed?.textForAi||''),m=text.match(/(?:SALDO\s+(?:FINAL|DISPON[IÍ]VEL)(?:\s+DO\s+PER[IÍ]ODO)?)[^\d-]*([\d.]+,\d{2})/i);const closing=validation?.expected?.closing??(m?amount(m[1]):null),key=clean(parsed?.metadata?.document||parsed?.metadata?.name||name.replace(/\d{2,4}[-_.]\d{1,2}[-_.]\d{1,2}/g,'').replace(/\.(pdf|xlsx?|csv)$/i,''));return{...validation,accountKey:key||clean(name),holderName:parsed?.metadata?.name||null,closing,expected:{...(validation.expected||{}),...(closing!==null?{closing}:{})}}}

async function importOne(cid:string,type:string,f:any,company:any){const fileHash=hash(f.buffer),dup=await pool!.query(`SELECT id,kind,status,status_detail,record_count,validation_status FROM source_files WHERE company_id=$1 AND hash=$2 LIMIT 1`,[cid,fileHash]);if(dup.rowCount){const d=dup.rows[0],records=n(d.record_count),label=TYPES[d.kind]||d.kind||'outra origem';if(d.kind!==type)return{name:f.originalname,status:'DUPLICATE',kind:d.kind,records,sourceFileId:d.id,detail:`Este conteúdo já foi importado como ${label}. Para trocar a função, descarte a importação anterior e processe novamente.`};if(d.status==='IMPORTED'&&records>0)return{name:f.originalname,status:'DUPLICATE',kind:d.kind,records,sourceFileId:d.id,detail:`Arquivo já importado como ${label} (${records} registro(s)).`};return{name:f.originalname,status:'REVIEW',kind:d.kind,records,sourceFileId:d.id,detail:`Este arquivo já foi enviado, mas a importação anterior ficou com ${records} registro(s). Abra o diagnóstico do arquivo e use Reprocessar.`}}const ext=path.extname(f.originalname).toLowerCase();if(['PAYABLES','RECEIVABLES'].includes(type)&&!['.xlsx','.xls','.csv'].includes(ext))throw new Error(`${TYPES[type]} usa o modelo Excel/CSV da Clara.`)
  let parsed:any=null,rows:any[]=[],validation:any={status:'OK'},records=0,periodStart:any=null,periodEnd:any=null
  if(type==='SALES_REPORT'&&['.xlsx','.xls','.csv'].includes(ext))rows=parseSales(f.buffer);else if(type==='PAYABLES'||type==='RECEIVABLES')rows=parseModel(f.buffer,type as any);else parsed=ext==='.pdf'?await parsePdf(f.buffer):parseTabular(f.buffer)
  if(parsed&&!parsed.transactions?.length&&parsed.textForAi){try{const adapted=await adaptUnknownPdf({text:parsed.textForAi,company});if(adapted?.transactions?.length)parsed.transactions=adapted.transactions.map((x:any)=>({occurredAt:x.date,competenceAt:x.date,description:x.description,amount:x.amount,direction:x.direction,paymentMethod:x.payment_method,financialStatus:'PAID',raw:{source:'ai_pdf_adapter',documentType:adapted.document_type,confidence:adapted.confidence}}))}catch(e){console.error('v080 pdf adapter',e)}}
  if(parsed){validation=type==='BANK_STATEMENT'?closingInfo(parsed,f.originalname):parsed.validation||{status:'OK'};periodStart=parsed.metadata?.periodStart;periodEnd=parsed.metadata?.periodEnd}
  const sf=await pool!.query(`INSERT INTO source_files(company_id,name,hash,kind,status,status_detail,record_count,confidence,validation_status,validation,period_start,period_end,content,mime_type,import_scope) VALUES($1,$2,$3,$4,'IMPORTED','Processando...',0,$5,$6,$7::jsonb,$8::date,$9::date,$10,$11,'GENERAL') RETURNING id`,[cid,f.originalname,fileHash,type,parsed?.confidence||90,validation.status||'OK',JSON.stringify(validation),periodStart||null,periodEnd||null,f.buffer,f.mimetype]);const sourceFileId=sf.rows[0].id
  try{
    if(type==='SALES_REPORT'){
      if(!rows.length&&parsed)rows=(parsed.transactions||[]).filter((x:any)=>n(x.amount)>0).map((x:any)=>({date:iso(x.competenceAt||x.occurredAt),customer:x.normalizedParty||'',description:x.description||'Venda',amount:Math.abs(n(x.amount)),paymentMethod:x.paymentMethod||'',dueDate:iso(x.dueAt),splits:[],raw:x.raw||{}}))
      for(let i=0;i<rows.length;i++){const r=rows[i],saleKey=hash(cid,'SALE',r.date,r.customer,r.description,r.amount,i),exists=await pool!.query(`SELECT id FROM transactions WHERE company_id=$1 AND economic_key=$2 AND accounting_role='SALE_ECONOMIC' LIMIT 1`,[cid,saleKey]);if(!exists.rowCount){const acc=await accountFor(cid,'Receita de vendas','ENTRADA');await tx(cid,{sourceFileId,occurredAt:r.date,competenceAt:r.date,description:r.description||`Venda ${r.customer||''}`,normalizedParty:String(r.customer||'').toUpperCase()||null,direction:'ENTRADA',amount:Math.abs(r.amount),category:'Receita de vendas',accountId:acc?.id,paymentMethod:r.paymentMethod,financialStatus:'EARNED',dreImpact:true,cashImpact:false,role:'SALE_ECONOMIC',economicKey:saleKey,raw:{source:'sales_report',customer:r.customer,paymentMethod:r.paymentMethod,splits:r.splits}});records++}
        const splits=(r.splits||[]).filter((s:any)=>n(s.amount)>0),sum=splits.reduce((a:number,s:any)=>a+n(s.amount),0),effective=splits.length&&Math.abs(sum-r.amount)<0.02?splits:[{method:r.paymentMethod||'A definir',amount:r.amount,pendingSplit:splits.length>0||/[+/&,]/.test(r.paymentMethod||'')}]
        for(let j=0;j<effective.length;j++){const s=effective[j],immediate=/PIX|CART|DINHEIRO/i.test(s.method||'');await insertReceivableControl(cid,{saleKey,index:j,customer:r.customer,description:`${r.description||'Venda'} · ${s.method||'Recebimento'}`,issueDate:r.date,competenceDate:r.date,dueDate:r.dueDate||(immediate?r.date:null),amount:s.amount,paymentMethod:s.method,category:'Receita de vendas',raw:{source:'sales_report',pendingDue:!r.dueDate&&!immediate,pendingSplit:Boolean(s.pendingSplit)}},sourceFileId)}
      }
    }else if(type==='BANK_STATEMENT'||type==='CARD_MACHINE_STATEMENT'){
      for(const r of parsed?.transactions||[]){const dir=r.direction==='SAIDA'?'SAIDA':'ENTRADA',value=dir==='SAIDA'?-Math.abs(n(r.amount)):Math.abs(n(r.amount)),c=await classify({...r,direction:dir,amount:value},cid,type==='BANK_STATEMENT'?{...company,bankHolderName:parsed?.metadata?.name||validation?.holderName||null}:company),category=c.category||'A classificar',acc=category&&category!=='A classificar'?await accountFor(cid,category,dir):null;await tx(cid,{sourceFileId,occurredAt:iso(r.occurredAt),competenceAt:iso(r.competenceAt||r.occurredAt),dueAt:iso(r.dueAt||r.occurredAt),paidAt:type==='BANK_STATEMENT'?r.paidAt||r.occurredAt:null,description:r.description||'Movimentação',normalizedParty:c.normalized_party,document:c.counterparty_document,direction:dir,amount:value,grossAmount:r.grossAmount,feeAmount:r.feeAmount,netAmount:r.netAmount,category,accountId:acc?.id||c.account_id,confidence:c.confidence,classificationStatus:c.status,classificationSource:c.source,paymentMethod:r.paymentMethod,financialStatus:type==='BANK_STATEMENT'?'PAID':'EVIDENCE',dreImpact:false,cashImpact:type==='BANK_STATEMENT',role:type==='BANK_STATEMENT'?'CASH_MOVEMENT':'CARD_EVIDENCE',externalId:r.externalId,raw:{...r.raw,user_document_type:type}});records++}
    }else if(type==='CREDIT_CARD_INVOICE'){
      for(const r of parsed?.transactions||[]){const info=installmentInfo(r.description),purchaseDate=iso(r.competenceAt||r.occurredAt)!,installmentValue=Math.abs(n(r.amount)),totalValue=installmentValue*Math.max(1,info.total),economicKey=hash(cid,'CARD_PURCHASE',purchaseDate,clean(info.base),totalValue.toFixed(2)),c=await classify({...r,direction:'SAIDA',amount:-totalValue},cid,company),category=c.category||'A classificar',acc=category!=='A classificar'?await accountFor(cid,category,'SAIDA'):null,exists=await pool!.query(`SELECT id FROM transactions WHERE company_id=$1 AND economic_key=$2 AND accounting_role='CARD_PURCHASE_ECONOMIC' LIMIT 1`,[cid,economicKey]);if(!exists.rowCount){await tx(cid,{sourceFileId,occurredAt:purchaseDate,competenceAt:purchaseDate,description:info.base||r.description,direction:'SAIDA',amount:-totalValue,category,accountId:acc?.id||c.account_id,confidence:c.confidence,classificationStatus:c.status,classificationSource:c.source,paymentMethod:'Cartão de crédito',financialStatus:'PURCHASED',dreImpact:true,cashImpact:false,role:'CARD_PURCHASE_ECONOMIC',economicKey,raw:{source:'credit_card_invoice',installments:info.total,installmentValue}});records++}const currentDue=iso(r.dueAt)||purchaseDate;for(let k=info.current;k<=info.total;k++)await insertPayableControl(cid,{economicKey,installment:k,totalInstallments:info.total,competenceDate:purchaseDate,dueDate:addMonths(currentDue,k-info.current),amount:installmentValue,description:`${info.base||r.description} · parcela ${k}/${info.total}`,invoiceRef:`${k}/${info.total}`},sourceFileId)}
    }else if(type==='PAYABLES'){for(const r of rows){if(await insertPayableEconomic(cid,{...r,originType:'FILES'},sourceFileId,company))records++}}
    else if(type==='RECEIVABLES'){for(let i=0;i<rows.length;i++){const r=rows[i];if(await insertReceivableControl(cid,{saleKey:hash(cid,'IMPORTED_REC',r.party,r.description,r.competenceDate,r.amount,i),index:i,customer:r.party,document:r.document,description:r.description,issueDate:r.issueDate,competenceDate:r.competenceDate||r.issueDate,dueDate:r.dueDate,amount:r.amount,paymentMethod:r.paymentMethod,category:r.category||'Receita de vendas',invoiceRef:r.invoiceRef,originType:'FILES',raw:r.raw},sourceFileId))records++}}
    const status=records?'IMPORTED':'REVIEW',detail=records?`${records} registro(s) processado(s).`:'Nenhum registro pôde ser extraído. Clique no alerta para revisar.';await pool!.query(`UPDATE source_files SET status=$3,status_detail=$4,record_count=$5,validation_status=$6,validation=$7::jsonb,processed_at=now() WHERE id=$1 AND company_id=$2`,[sourceFileId,cid,status,detail,records,records?(validation.status||'OK'):'ERROR',JSON.stringify(records?validation:{...validation,error:detail})]);await pool!.query(`INSERT INTO expected_sources(company_id,kind,label) VALUES($1,$2,$3) ON CONFLICT(company_id,kind) DO UPDATE SET label=excluded.label,active=true`,[cid,type,TYPES[type]]);return{name:f.originalname,status,kind:type,records,detail}
  }catch(e){await pool!.query(`UPDATE source_files SET status='REVIEW',validation_status='ERROR',status_detail=$3,validation=$4::jsonb WHERE id=$1 AND company_id=$2`,[sourceFileId,cid,String((e as any)?.message||e),JSON.stringify({error:String((e as any)?.message||e)})]);throw e}
}

export async function autoReconcile(cid:string,from:string,to:string){const [receivables,payables,cash,links]=await Promise.all([
  pool!.query(`SELECT r.id,r.transaction_id,r.customer,r.description,r.issue_date,r.due_date,r.amount,r.payment_method FROM receivables r WHERE r.company_id=$1 AND r.receipt_status<>'RECEIVED' AND (r.issue_date BETWEEN $2::date-interval '15 days' AND $3::date+interval '15 days' OR r.due_date BETWEEN $2::date-interval '15 days' AND $3::date+interval '15 days')`,[cid,from,to]),
  pool!.query(`SELECT p.id,p.transaction_id,p.supplier,p.description,p.issue_date,p.due_date,p.amount FROM payables p WHERE p.company_id=$1 AND p.payment_status<>'PAID' AND p.origin_type<>'CREDIT_CARD_INSTALLMENT' AND p.due_date BETWEEN $2::date-interval '15 days' AND $3::date+interval '15 days'`,[cid,from,to]),
  pool!.query(`SELECT id,occurred_at,competence_at,description,direction,amount,payment_method,category FROM transactions WHERE company_id=$1 AND accounting_role IN ('CASH_MOVEMENT','DIRECT_BANK_INCOME','DIRECT_BANK_EXPENSE') AND competence_at BETWEEN $2::date-interval '15 days' AND $3::date+interval '15 days' ORDER BY competence_at,id`,[cid,from,to]),
  pool!.query(`SELECT left_transaction_id,right_transaction_id FROM reconciliation_links WHERE company_id=$1`,[cid])])
  const linked=new Set<string>(),usedCash=new Set<string>();for(const l of links.rows){linked.add(String(l.left_transaction_id));linked.add(String(l.right_transaction_id));usedCash.add(String(l.right_transaction_id))}
  const match=async(item:any,dir:string,kind:string)=>{if(!item.transaction_id||linked.has(String(item.transaction_id)))return false;const base=iso(item.due_date||item.issue_date),candidates=cash.rows.filter((c:any)=>c.direction===dir&&!usedCash.has(String(c.id))&&Math.abs(Math.abs(n(c.amount))-Math.abs(n(item.amount)))<0.02&&base&&dayDiff(c.competence_at||c.occurred_at,base)<=10);if(candidates.length!==1)return false;const c=candidates[0];await pool!.query(`INSERT INTO reconciliation_links(company_id,left_transaction_id,right_transaction_id,match_type,confidence) VALUES($1,$2,$3,$4,98) ON CONFLICT(company_id,left_transaction_id,right_transaction_id) DO NOTHING`,[cid,item.transaction_id,c.id,kind]);usedCash.add(String(c.id));linked.add(String(item.transaction_id));linked.add(String(c.id));if(kind==='RECEIVABLE_CASH')await pool!.query(`UPDATE receivables SET receipt_status='RECEIVED',received_amount=amount,received_at=COALESCE(received_at,$3::timestamptz),updated_at=now() WHERE id=$1 AND company_id=$2`,[item.id,cid,c.occurred_at||c.competence_at]);else await pool!.query(`UPDATE payables SET payment_status='PAID',paid_amount=amount,paid_at=COALESCE(paid_at,$3::timestamptz),updated_at=now() WHERE id=$1 AND company_id=$2`,[item.id,cid,c.occurred_at||c.competence_at]);return true}
  let matched=0;for(const r of receivables.rows)if(await match(r,'ENTRADA','RECEIVABLE_CASH'))matched++;for(const p of payables.rows)if(await match(p,'SAIDA','PAYABLE_CASH'))matched++;return matched}

export async function initV080Schema(){if(!pool)return false
  await pool.query(`ALTER TABLE payables ADD COLUMN IF NOT EXISTS competence_date DATE`);await pool.query(`ALTER TABLE receivables ADD COLUMN IF NOT EXISTS competence_date DATE`);await pool.query(`ALTER TABLE receivables ALTER COLUMN due_date DROP NOT NULL`)
  await pool.query(`UPDATE payables SET competence_date=COALESCE(competence_date,issue_date,due_date) WHERE competence_date IS NULL`);await pool.query(`UPDATE receivables SET competence_date=COALESCE(competence_date,issue_date,due_date) WHERE competence_date IS NULL`)
  await pool.query(`UPDATE transactions t SET dre_impact=false,cash_impact=true,accounting_role='CASH_MOVEMENT' FROM source_files sf WHERE t.source_file_id=sf.id AND t.company_id=sf.company_id AND sf.kind='BANK_STATEMENT' AND t.accounting_role NOT IN ('DIRECT_BANK_EXPENSE','DIRECT_BANK_INCOME','TRANSFER')`)
  await pool.query(`UPDATE transactions t SET dre_impact=false,cash_impact=false,accounting_role='CARD_EVIDENCE' FROM source_files sf WHERE t.source_file_id=sf.id AND t.company_id=sf.company_id AND sf.kind='CARD_MACHINE_STATEMENT'`)
  await pool.query(`CREATE TABLE IF NOT EXISTS recurring_expenses(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID REFERENCES companies(id) ON DELETE CASCADE,supplier TEXT,description TEXT NOT NULL,expected_amount NUMERIC(14,2) NOT NULL,due_day INT NOT NULL DEFAULT 10,category TEXT,account_id UUID REFERENCES chart_accounts(id) ON DELETE SET NULL,payment_method TEXT,start_date DATE DEFAULT current_date,months_ahead INT DEFAULT 12,active BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`)
  await pool.query(`CREATE OR REPLACE FUNCTION clara_sync_payable_tx() RETURNS trigger AS $$ BEGIN IF NEW.transaction_id IS NOT NULL THEN UPDATE transactions SET amount=-abs(NEW.amount),competence_at=COALESCE(NEW.competence_date,NEW.issue_date,NEW.due_date),due_at=NEW.due_date,category=COALESCE(NEW.category,category),account_id=COALESCE(NEW.account_id,account_id),financial_status=CASE WHEN NEW.payment_status='PAID' THEN 'PAID' ELSE financial_status END,paid_at=CASE WHEN NEW.payment_status='PAID' THEN COALESCE(NEW.paid_at,paid_at,now()) ELSE paid_at END WHERE id=NEW.transaction_id AND company_id=NEW.company_id; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql`)
  await pool.query(`DROP TRIGGER IF EXISTS trg_clara_sync_payable_tx ON payables; CREATE TRIGGER trg_clara_sync_payable_tx AFTER UPDATE ON payables FOR EACH ROW EXECUTE FUNCTION clara_sync_payable_tx()`)
  try{await pool.query(`INSERT INTO schema_meta(key,value) VALUES('schema_version','0.8.0') ON CONFLICT(key) DO UPDATE SET value='0.8.0'`)}catch{}
  return true
}

export function registerV080Routes(app:any){
  app.post('/api/import-v080',collectUploads,async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const type=String(req.query?.type||'').toUpperCase();if(!TYPES[type])return res.status(400).json({message:'Tipo de arquivo inválido.'});if(!req.uploadedFiles?.length)return res.status(400).json({message:'Nenhum arquivo recebido.'});const company=await getCompany(req.companyId),results:any[]=[];for(const f of req.uploadedFiles)try{results.push(await importOne(req.companyId,type,f,company))}catch(e:any){results.push({name:f.originalname,status:'ERROR',detail:e?.message||String(e)})}res.json({message:`${results.filter(x=>x.status==='IMPORTED').length} arquivo(s) processado(s).`,results})})

  app.post('/api/payables-v080',async(req:any,res:any)=>{if(!pool)return res.status(503).json({message:'Banco não configurado.'});const b=req.body||{},company=await getCompany(req.companyId);if(!b.description||!n(b.amount))return res.status(400).json({message:'Informe descrição e valor.'});const out=await insertPayableEconomic(req.companyId,{party:b.supplier,document:b.supplierDocument,description:b.description,issueDate:b.issueDate||b.competenceDate||b.dueDate,competenceDate:b.competenceDate||b.issueDate||b.dueDate,dueDate:b.dueDate,amount:n(b.amount),category:b.category,accountId:b.accountId,paymentMethod:b.paymentMethod,invoiceRef:b.invoiceRef,originType:'MANUAL'},null,company);res.json({ok:true,id:out?.id})})

  app.get('/api/recurring-expenses',async(req:any,res:any)=>{const r=await pool!.query(`SELECT * FROM recurring_expenses WHERE company_id=$1 ORDER BY active DESC,description`,[req.companyId]);res.json(r.rows)})
  app.post('/api/recurring-expenses',async(req:any,res:any)=>{const b=req.body||{},value=Math.abs(n(b.amount)),day=Math.max(1,Math.min(28,Number(b.dueDay||10))),months=Math.max(1,Math.min(24,Number(b.monthsAhead||12)));if(!b.description||!value)return res.status(400).json({message:'Informe descrição e valor médio.'});const r=await pool!.query(`INSERT INTO recurring_expenses(company_id,supplier,description,expected_amount,due_day,category,account_id,payment_method,start_date,months_ahead) VALUES($1,$2,$3,$4,$5,$6,$7,$8,COALESCE($9::date,current_date),$10) RETURNING *`,[req.companyId,b.supplier||null,b.description,value,day,b.category||null,b.accountId||null,b.paymentMethod||null,b.startDate||null,months]);const company=await getCompany(req.companyId),start=iso(r.rows[0].start_date)||iso(new Date())!;for(let i=0;i<months;i++){const month=addMonths(start,i).slice(0,7),due=`${month}-${pad(day)}`,competence=`${month}-01`;await insertPayableEconomic(req.companyId,{party:b.supplier,description:b.description,issueDate:competence,competenceDate:competence,dueDate:due,amount:value,category:b.category,accountId:b.accountId,paymentMethod:b.paymentMethod,originType:'RECURRING',raw:{recurringExpenseId:r.rows[0].id,provision:true}},null,company)}res.json(r.rows[0])})
  app.patch('/api/recurring-expenses/:id',async(req:any,res:any)=>{const b=req.body||{},r=await pool!.query(`UPDATE recurring_expenses SET supplier=COALESCE($3,supplier),description=COALESCE($4,description),expected_amount=COALESCE($5,expected_amount),due_day=COALESCE($6,due_day),category=COALESCE($7,category),account_id=COALESCE($8,account_id),payment_method=COALESCE($9,payment_method),active=COALESCE($10,active),updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING *`,[req.params.id,req.companyId,b.supplier??null,b.description??null,b.amount??null,b.dueDay??null,b.category??null,b.accountId??null,b.paymentMethod??null,b.active??null]);if(!r.rowCount)return res.status(404).json({message:'Despesa fixa não encontrada.'});res.json(r.rows[0])})

  app.get('/api/cash-flow-v080',async(req:any,res:any)=>{const today=iso(new Date())!,files=await pool!.query(`SELECT id,name,validation,created_at FROM source_files WHERE company_id=$1 AND kind='BANK_STATEMENT' AND status='IMPORTED' ORDER BY created_at DESC`,[req.companyId]),latest=new Map<string,any>();for(const f of files.rows){const v=f.validation||{},key=String(v.accountKey||f.name),rawClosing=v.closing??v.expected?.closing,closing=rawClosing===null||rawClosing===undefined?null:Number(rawClosing);if(!latest.has(key))latest.set(key,{...f,closing,accountKey:key})}let balances=[...latest.values()].filter(x=>x.closing!==null&&Number.isFinite(x.closing)),available=balances.reduce((a,x)=>a+n(x.closing),0),availabilitySource='BANK_BALANCES';if(!balances.length){const q=await pool!.query(`SELECT COALESCE(sum(amount),0)::numeric total FROM transactions WHERE company_id=$1 AND cash_impact=true`,[req.companyId]);available=n(q.rows[0]?.total);availabilitySource='MOVEMENT_ESTIMATE'}const [pay,rec]=await Promise.all([pool!.query(`SELECT id,supplier party,description,due_date,amount,'PAYABLE' kind FROM payables WHERE company_id=$1 AND payment_status<>'PAID' ORDER BY due_date NULLS LAST`,[req.companyId]),pool!.query(`SELECT id,customer party,description,due_date,amount-COALESCE(received_amount,0) amount,'RECEIVABLE' kind FROM receivables WHERE company_id=$1 AND receipt_status<>'RECEIVED' ORDER BY due_date NULLS LAST`,[req.companyId])]);const days=(d:any)=>d?Math.ceil((new Date(`${iso(d)}T12:00:00`).getTime()-new Date(`${today}T12:00:00`).getTime())/86400000):9999,horizons=[7,30,60,90,365].map(h=>{const incoming=rec.rows.filter((x:any)=>days(x.due_date)>=0&&days(x.due_date)<=h).reduce((a:number,x:any)=>a+n(x.amount),0),outgoing=pay.rows.filter((x:any)=>days(x.due_date)>=0&&days(x.due_date)<=h).reduce((a:number,x:any)=>a+n(x.amount),0);return{days:h,incoming,outgoing,projected:available+incoming-outgoing}}),overdueReceivable=rec.rows.filter((x:any)=>x.due_date&&days(x.due_date)<0).reduce((a:number,x:any)=>a+n(x.amount),0),overduePayable=pay.rows.filter((x:any)=>x.due_date&&days(x.due_date)<0).reduce((a:number,x:any)=>a+n(x.amount),0),upcoming=[...pay.rows,...rec.rows].filter((x:any)=>!x.due_date||days(x.due_date)>=0).sort((a:any,b:any)=>String(a.due_date||'9999').localeCompare(String(b.due_date||'9999'))).slice(0,60);res.json({today,available,availabilitySource,balances:balances.map(x=>({name:x.name,accountKey:x.accountKey,balance:x.closing,updatedAt:x.created_at})),horizons,overdueReceivable,overduePayable,upcoming})})

  app.get('/api/reconciliation-v080',async(req:any,res:any)=>{const period=/^\d{4}-\d{2}$/.test(String(req.query?.period||''))?String(req.query.period):iso(new Date())!.slice(0,7),[y,m]=period.split('-').map(Number),from=`${period}-01`,to=`${period}-${pad(new Date(y,m,0).getDate())}`;const autoMatched=await autoReconcile(req.companyId,from,to),[links,openRec,openPay,unmatchedCash]=await Promise.all([pool!.query(`SELECT rl.id,rl.match_type,rl.confidence,l.description left_description,l.amount left_amount,r.description right_description,r.amount right_amount FROM reconciliation_links rl JOIN transactions l ON l.id=rl.left_transaction_id JOIN transactions r ON r.id=rl.right_transaction_id WHERE rl.company_id=$1 AND (l.competence_at BETWEEN $2::date AND $3::date OR r.competence_at BETWEEN $2::date AND $3::date) ORDER BY rl.created_at DESC LIMIT 80`,[req.companyId,from,to]),pool!.query(`SELECT r.id,r.transaction_id,r.customer party,r.description,r.issue_date,r.due_date,r.amount,r.payment_method FROM receivables r WHERE r.company_id=$1 AND r.receipt_status<>'RECEIVED' AND r.competence_date BETWEEN $2::date AND $3::date ORDER BY r.issue_date`,[req.companyId,from,to]),pool!.query(`SELECT p.id,p.transaction_id,p.supplier party,p.description,p.issue_date,p.due_date,p.amount,p.payment_method FROM payables p WHERE p.company_id=$1 AND p.payment_status<>'PAID' AND p.competence_date BETWEEN $2::date AND $3::date ORDER BY p.due_date`,[req.companyId,from,to]),pool!.query(`SELECT t.id,t.source_file_id,t.description,t.normalized_party,t.competence_at,t.direction,t.amount,t.category,t.account_id,t.classification_status,t.payment_method,sf.validation->>'holderName' holder_name FROM transactions t LEFT JOIN source_files sf ON sf.id=t.source_file_id WHERE t.company_id=$1 AND t.accounting_role='CASH_MOVEMENT' AND t.competence_at BETWEEN $2::date AND $3::date AND NOT EXISTS(SELECT 1 FROM reconciliation_links rl WHERE rl.company_id=$1 AND (rl.left_transaction_id=t.id OR rl.right_transaction_id=t.id)) AND NOT EXISTS(SELECT 1 FROM reconciliation_ignores ri WHERE ri.company_id=$1 AND ri.transaction_id=t.id) ORDER BY t.competence_at`,[req.companyId,from,to])]);res.json({period,autoMatched,matches:links.rows,openReceivables:openRec.rows,openPayables:openPay.rows,unmatchedCash:unmatchedCash.rows,summary:{matched:links.rowCount,receivable:openRec.rowCount,payable:openPay.rowCount,cash:unmatchedCash.rowCount}})})
  app.post('/api/reconciliation-v080/link',async(req:any,res:any)=>{const{controlId,cashId}=req.body||{},ok=await pool!.query(`SELECT id,accounting_role FROM transactions WHERE company_id=$1 AND id=ANY($2::uuid[])`,[req.companyId,[controlId,cashId]]);if(ok.rowCount<2)return res.status(400).json({message:'Movimentação inválida.'});await pool!.query(`INSERT INTO reconciliation_links(company_id,left_transaction_id,right_transaction_id,match_type,confidence) VALUES($1,$2,$3,'MANUAL_V081',100) ON CONFLICT(company_id,left_transaction_id,right_transaction_id) DO UPDATE SET confidence=100,match_type='MANUAL_V081'`,[req.companyId,controlId,cashId]);const c=await pool!.query(`SELECT occurred_at,competence_at FROM transactions WHERE id=$1`,[cashId]),dt=c.rows[0]?.occurred_at||c.rows[0]?.competence_at;await pool!.query(`UPDATE receivables SET receipt_status='RECEIVED',received_amount=amount,received_at=$3,updated_at=now() WHERE company_id=$1 AND transaction_id=$2`,[req.companyId,controlId,dt]);await pool!.query(`UPDATE payables SET payment_status='PAID',paid_amount=amount,paid_at=$3,updated_at=now() WHERE company_id=$1 AND transaction_id=$2`,[req.companyId,controlId,dt]);await pool!.query(`UPDATE transactions SET dre_impact=false,accounting_role='CASH_MOVEMENT' WHERE id=$1 AND company_id=$2 AND accounting_role IN ('DIRECT_BANK_INCOME','DIRECT_BANK_EXPENSE')`,[cashId,req.companyId]);res.json({ok:true})})
  app.post('/api/reconciliation-v080/direct-economic',async(req:any,res:any)=>{const id=req.body?.transactionId,r=await pool!.query(`SELECT * FROM transactions WHERE id=$1 AND company_id=$2 AND accounting_role='CASH_MOVEMENT' LIMIT 1`,[id,req.companyId]);if(!r.rowCount)return res.status(404).json({message:'Movimentação bancária não encontrada.'});const t=r.rows[0],dir=t.direction==='SAIDA'?'SAIDA':'ENTRADA',accountId=String(req.body?.accountId||''),company=await getCompany(req.companyId);let category=req.body?.category||t.category||null,acc:any=null;if(accountId){const ar=await pool!.query(`SELECT id,name,dre_section FROM chart_accounts WHERE id=$1 AND company_id=$2 AND active=true AND is_group=false LIMIT 1`,[accountId,req.companyId]);if(!ar.rowCount)return res.status(400).json({message:'Selecione um plano de contas válido.'});acc=ar.rows[0];category=acc.name}else{const sf=t.source_file_id?await pool!.query(`SELECT validation FROM source_files WHERE id=$1 AND company_id=$2 LIMIT 1`,[t.source_file_id,req.companyId]):null,holder=clean(sf?.rows?.[0]?.validation?.holderName||''),party=clean(t.normalized_party||''),pix=/PIX/.test(clean(t.payment_method||t.description||'')),own=holder&&party&&(holder.includes(party)||party.includes(holder));if(dir==='ENTRADA'&&pix&&!own)category='Receita de vendas';const c=await classify(t,req.companyId,{...company,bankHolderName:sf?.rows?.[0]?.validation?.holderName||null});category=category||c.category||(dir==='ENTRADA'?'Outras receitas':'Outras despesas');acc=await accountFor(req.companyId,category,dir)}const date=iso(t.competence_at||t.occurred_at),isTransfer=category==='Transferência entre contas próprias',dre=Boolean(acc?.dre_section!=='FORA_DRE')&&!isTransfer&&!['Aporte / Empréstimo','Liquidação de cartão de crédito','Retirada do sócio'].includes(category);await pool!.query(`UPDATE transactions SET competence_at=$3::date,due_at=$3::date,paid_at=COALESCE(paid_at,$3::date),category=$4,account_id=$5,classification_status='CONFIRMED',classification_source='DIRECT_BANK_V081',dre_impact=$6,cash_impact=true,accounting_role=$7 WHERE id=$1 AND company_id=$2`,[id,req.companyId,date,category,acc?.id||null,dre,isTransfer?'TRANSFER':dir==='ENTRADA'?'DIRECT_BANK_INCOME':'DIRECT_BANK_EXPENSE']);res.json({ok:true,category})})
}
