import fs from'node:fs'

function mustReplace(text,from,to,label){if(!text.includes(from))throw new Error(`Anchor not found: ${label}`);return text.replace(from,to)}
function setVersion(file){const j=JSON.parse(fs.readFileSync(file,'utf8'));j.version='0.8.0';fs.writeFileSync(file,JSON.stringify(j,null,2)+'\n')}

const v070Path='client/src/v070.tsx'
let v070=fs.readFileSync(v070Path,'utf8')
v070=mustReplace(v070,"const docTypes=[['BANK_STATEMENT','Extrato Bancário'],['CARD_MACHINE_STATEMENT','Extrato Maquineta Cartão'],['CREDIT_CARD_INVOICE','Fatura Cartão de Crédito'],['PAYABLES','Contas a Pagar'],['RECEIVABLES','Contas a Receber']]","const docTypes=[['BANK_STATEMENT','Extrato Bancário'],['CARD_MACHINE_STATEMENT','Extrato Maquineta Cartão'],['CREDIT_CARD_INVOICE','Fatura Cartão de Crédito'],['SALES_REPORT','Relatório de Vendas / Caixa'],['PAYABLES','Contas a Pagar'],['RECEIVABLES','Contas a Receber']]",'v070 docTypes')
v070=mustReplace(v070,"const guessType=(name:string)=>{const s=name.toLowerCase();if(/receber|cliente|contas.?receb/.test(s))return'RECEIVABLES';if(/pagar|fornecedor|contas.?pag/.test(s))return'PAYABLES';if(/fatura|credit|cartao/.test(s)&&!/pagbank|stone|cielo|rede/.test(s))return'CREDIT_CARD_INVOICE';if(/pagbank|stone|cielo|rede|maquin/.test(s))return'CARD_MACHINE_STATEMENT';return'BANK_STATEMENT'}","const guessType=(name:string)=>{const s=name.toLowerCase();if(/relatorio.*venda|vendas.*caixa|faturamento|venda.?dia/.test(s))return'SALES_REPORT';if(/receber|cliente|contas.?receb/.test(s))return'RECEIVABLES';if(/pagar|fornecedor|contas.?pag/.test(s))return'PAYABLES';if(/fatura|credit|cartao/.test(s)&&!/pagbank|stone|cielo|rede/.test(s))return'CREDIT_CARD_INVOICE';if(/pagbank|stone|cielo|rede|maquin/.test(s))return'CARD_MACHINE_STATEMENT';return'BANK_STATEMENT'}",'v070 guessType')
v070=mustReplace(v070,"  CREDIT_CARD_INVOICE:'Compras, parcelas, encargos e fechamento das faturas de cartão de crédito.',\n  PAYABLES:","  CREDIT_CARD_INVOICE:'Compras, parcelas, encargos e fechamento das faturas de cartão de crédito.',\n  SALES_REPORT:'Faturamento por competência: data da venda, cliente, valor e forma de pagamento. É a fonte principal da receita na DRE.',\n  PAYABLES:",'v070 orchestration copy')
v070=v070.replaceAll("/api/import-classified?type=","/api/import-v080?type=")
v070=v070.replace('Contas a Pagar e Contas a Receber usam planilhas padronizadas. Extratos e faturas podem ser enviados em PDF, Excel ou CSV.','Contas a Pagar e Contas a Receber usam planilhas padronizadas. Extratos, faturas e Relatório de Vendas/Caixa podem ser enviados em PDF, Excel ou CSV.')
fs.writeFileSync(v070Path,v070)

const mainPath='client/src/main.tsx'
let main=fs.readFileSync(mainPath,'utf8')
main=mustReplace(main,"import{FilesPageV070,PayablesPageV070,ReceivablesPage,ReconciliationPageV070,PresentationPage,DemoSessionGate,DemoNotice}from'./v070'","import{FilesPageV070,PresentationPage,DemoSessionGate,DemoNotice}from'./v070'\nimport{CashFlowPageV080,PayablesPageV080,ReceivablesPageV080,ReconciliationPageV080}from'./v080'\nimport{CashAvailabilityCard}from'./v080dash'",'main imports')
main=mustReplace(main,"type Page='resumo'|'arquivos'|'lancamentos'|'conciliacao'|'dre'|'contas_pagar'|'contas_receber'|'precificacao'|'apresentacao'|'cadastros'|'configuracoes'|'administracao'","type Page='resumo'|'arquivos'|'lancamentos'|'conciliacao'|'contas_pagar'|'contas_receber'|'fluxo_caixa'|'dre'|'precificacao'|'apresentacao'|'cadastros'|'configuracoes'|'administracao'",'Page type')
main=main.replace("const APP_VERSION='0.7.1'","const APP_VERSION='0.8.0'")
main=mustReplace(main,"const SOURCE_TYPES=[['BANK_STATEMENT','Extrato Bancário'],['CARD_MACHINE_STATEMENT','Extrato Maquineta Cartão'],['CREDIT_CARD_INVOICE','Fatura Cartão de Crédito'],['PAYABLES','Contas a Pagar'],['RECEIVABLES','Contas a Receber']]","const SOURCE_TYPES=[['BANK_STATEMENT','Extrato Bancário'],['CARD_MACHINE_STATEMENT','Extrato Maquineta Cartão'],['CREDIT_CARD_INVOICE','Fatura Cartão de Crédito'],['SALES_REPORT','Relatório de Vendas / Caixa'],['PAYABLES','Contas a Pagar'],['RECEIVABLES','Contas a Receber']]",'main source types')
const navOld="  const nav:[Page,any,string][]=[['resumo',Home,'Resumo'],['arquivos',FolderOpen,'Arquivos'],['lancamentos',ListChecks,'Lançamentos'],['conciliacao',RefreshCcw,'Conciliação'],['dre',BarChart3,'DRE / Resultados'],['contas_pagar',WalletCards,'Contas a Pagar'],['contas_receber',ArrowDownRight,'Contas a Receber'],['precificacao',Calculator,'Precificação'],['apresentacao',FileSpreadsheet,'Apresentação'],['cadastros',Landmark,'Cadastros'],['configuracoes',Settings,'Configurações']]\n  if(session.user.role==='MASTER')nav.push(['administracao',Users,'Administração'])"
const navNew="  const nav:[Page,any,string,string][]=[['arquivos',FolderOpen,'Arquivos','ROTINA FINANCEIRA'],['lancamentos',ListChecks,'Lançamentos / Classificação','ROTINA FINANCEIRA'],['conciliacao',RefreshCcw,'Conciliação','ROTINA FINANCEIRA'],['contas_pagar',WalletCards,'Contas a Pagar','ROTINA FINANCEIRA'],['contas_receber',ArrowDownRight,'Contas a Receber','ROTINA FINANCEIRA'],['resumo',Home,'Resumo','GESTÃO'],['fluxo_caixa',Landmark,'Fluxo de Caixa','GESTÃO'],['dre',BarChart3,'DRE / Resultados','GESTÃO'],['apresentacao',FileSpreadsheet,'Apresentação','GESTÃO'],['precificacao',Calculator,'Precificação','GESTÃO'],['cadastros',Landmark,'Cadastros','ESTRUTURA'],['configuracoes',Settings,'Configurações','ESTRUTURA']]\n  if(session.user.role==='MASTER')nav.push(['administracao',Users,'Administração','ADMINISTRAÇÃO'])"
main=mustReplace(main,navOld,navNew,'main nav')
main=mustReplace(main,"    if(page==='conciliacao')return <ReconciliationPageV070 reconciliation={reconciliation} sourceHealth={sourceHealth} period={period} refresh={refresh}/>\n    if(page==='dre')return <DrePage dre={dre} dreComp={dreComp} dreMode={dreMode} setDreMode={setDreMode} period={period} status={status} closePeriod={closePeriod} reopenPeriod={reopenPeriod} canAdmin={canAdminCompany}/>\n    if(page==='contas_pagar')return <PayablesPageV070 period={period} chartAccounts={chartAccounts} canWrite={canWrite}/>\n    if(page==='contas_receber')return <ReceivablesPage period={period} chartAccounts={chartAccounts} canWrite={canWrite}/>","    if(page==='conciliacao')return <ReconciliationPageV080 period={period}/>\n    if(page==='contas_pagar')return <PayablesPageV080 period={period} chartAccounts={chartAccounts} canWrite={canWrite}/>\n    if(page==='contas_receber')return <ReceivablesPageV080 period={period} canWrite={canWrite}/>\n    if(page==='fluxo_caixa')return <CashFlowPageV080 period={period}/>\n    if(page==='dre')return <DrePage dre={dre} dreComp={dreComp} dreMode={dreMode} setDreMode={setDreMode} period={period} status={status} closePeriod={closePeriod} reopenPeriod={reopenPeriod} canAdmin={canAdminCompany}/>",'render v080 pages')
const navRenderOld="<nav>{nav.map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMobileMenu(false)}}><Icon/>{label}{id==='lancamentos'&&groups.length>0&&<span className=\"nav-count\">{groups.length}</span>}</button>)}</nav>"
const navRenderNew="<nav>{nav.map(([id,Icon,label,group],i)=><React.Fragment key={id}>{(i===0||nav[i-1]?.[3]!==group)&&<div className=\"nav-section-label\">{group}</div>}<button className={page===id?'active':''} onClick={()=>{setPage(id);setMobileMenu(false)}}><Icon/>{label}{id==='lancamentos'&&groups.length>0&&<span className=\"nav-count\">{groups.length}</span>}</button></React.Fragment>)}</nav>"
main=mustReplace(main,navRenderOld,navRenderNew,'sidebar nav render')
main=mustReplace(main,'<Kpi icon={Landmark} title="Caixa Disponível" value={fmt(data.summary?.balance)} sub="Movimento líquido" tone="green"/>','<CashAvailabilityCard onClick={()=>onGo(\'fluxo_caixa\')}/>','dashboard cash card')
fs.writeFileSync(mainPath,main)

const serverPath='server/src/index.ts'
let server=fs.readFileSync(serverPath,'utf8')
server=mustReplace(server,"import { registerV070Routes } from './v070.js'","import { registerV070Routes } from './v070.js'\nimport { registerV080Routes,initV080Schema } from './v080.js'\nimport { registerV080ExtraRoutes } from './v080extra.js'",'server imports')
server=mustReplace(server,'registerV070Routes(app)','registerV070Routes(app)\nregisterV080Routes(app)\nregisterV080ExtraRoutes(app)','register v080 routes')
server=mustReplace(server,'  await initDb()\n  await ensureMasterUser()','  await initDb()\n  await initV080Schema()\n  await ensureMasterUser()','init v080 schema')
server=server.replaceAll("version:'0.7.1'","version:'0.8.0'").replace('Clara BPO v0.7.1 on','Clara BPO v0.8.0 on')
fs.writeFileSync(serverPath,server)

const v080Path='server/src/v080.ts'
let v080=fs.readFileSync(v080Path,'utf8')
const migrationAnchor="  await pool.query(`UPDATE payables SET competence_date=COALESCE(competence_date,issue_date,due_date) WHERE competence_date IS NULL`);await pool.query(`UPDATE receivables SET competence_date=COALESCE(competence_date,issue_date,due_date) WHERE competence_date IS NULL`)"
const migrationNew=migrationAnchor+"\n  await pool.query(`UPDATE transactions t SET dre_impact=false,cash_impact=true,accounting_role='CASH_MOVEMENT' FROM source_files sf WHERE t.source_file_id=sf.id AND t.company_id=sf.company_id AND sf.kind='BANK_STATEMENT' AND t.accounting_role NOT IN ('DIRECT_BANK_EXPENSE','DIRECT_BANK_INCOME','TRANSFER')`)\n  await pool.query(`UPDATE transactions t SET dre_impact=false,cash_impact=false,accounting_role='CARD_EVIDENCE' FROM source_files sf WHERE t.source_file_id=sf.id AND t.company_id=sf.company_id AND sf.kind='CARD_MACHINE_STATEMENT'`)"
v080=mustReplace(v080,migrationAnchor,migrationNew,'legacy accounting migration')
fs.writeFileSync(v080Path,v080)

setVersion('package.json');setVersion('client/package.json');setVersion('server/package.json')
console.log('Clara v0.8.0 structural integration applied')
