import fs from 'node:fs'

const clientPath='client/src/v070.tsx'
let client=fs.readFileSync(clientPath,'utf8')
if(!client.includes("import'./v071.css'"))client=client.replace("import'./v070.css'","import'./v070.css'\nimport'./v071.css'")

const replacement=String.raw`const orchestrationCopy:any={
  BANK_STATEMENT:'Movimentações das contas bancárias: PIX, transferências, tarifas, pagamentos e recebimentos.',
  CARD_MACHINE_STATEMENT:'Vendas e recebimentos das adquirentes e maquininhas de cartão.',
  CREDIT_CARD_INVOICE:'Compras, parcelas, encargos e fechamento das faturas de cartão de crédito.',
  PAYABLES:'Títulos de fornecedores e compromissos futuros. Use o modelo Excel da Clara.',
  RECEIVABLES:'Títulos de clientes e recebimentos futuros. Use o modelo Excel da Clara.'
}
const fileKey=(file:any)=>[file.webkitRelativePath||file.name,file.size,file.lastModified].join('|')

function AssignmentPicker({type,pending,setPending,openType,setOpenType}:any){
  const selected=pending.filter((x:any)=>x.type===type),open=openType===type
  const label=selected.length===0?'Selecionar arquivos':selected.length===1?selected[0].file.name:selected.length+' arquivos selecionados'
  function toggle(item:any){setPending((items:any[])=>items.map(x=>x.key===item.key?{...x,type:x.type===type?'':type}:x))}
  return <div className="assignment-picker"><button type="button" className="assignment-trigger" aria-expanded={open} onClick={()=>setOpenType(open?null:type)}><span><b>{label}</b><small>{selected.length?'Clique para alterar a seleção':'Marque um ou mais arquivos disponíveis'}</small></span><span>Marcar / desmarcar ▾</span></button>{open&&<div className="assignment-menu">{pending.length===0?<div className="assignment-menu-empty">Selecione arquivos ou uma pasta acima.</div>:pending.map((item:any)=>{const checked=item.type===type,other=item.type&&item.type!==type,otherLabel=docTypes.find(x=>x[0]===item.type)?.[1];return <button type="button" className="assignment-option" key={item.key} onClick={()=>toggle(item)}><span className={'assignment-check '+(checked?'checked':'')}>{checked&&<Check/>}</span><span><b>{item.file.name}</b><small>{item.file.webkitRelativePath||Math.round(item.file.size/1024)+' KB'}</small></span>{other?<em>em {otherLabel}</em>:item.suggestion===type&&!checked?<em>Sugestão</em>:null}</button>})}</div>}</div>
}

export function FilesPageV070({sourceHealth,allSourceFiles,canWrite,folderRef,fileRef,refresh,onGoTransactions}:any){
  const[pending,setPending]=useState<any[]>([]),[processing,setProcessing]=useState(false),[reviewFile,setReviewFile]=useState<string|null>(null),[openType,setOpenType]=useState<string|null>(null)
  function stage(files:any){if(!files?.length)return;const incoming=[...files].filter((f:any)=>/\.(pdf|xlsx|xls|csv)$/i.test(f.name));setPending(prev=>{const map=new Map(prev.map((x:any)=>[x.key,x]));for(const file of incoming){const key=fileKey(file);if(!map.has(key))map.set(key,{file,key,type:'',suggestion:guessType(file.name)})}return[...map.values()]})}
  function suggest(){setPending(items=>items.map(x=>({...x,type:x.type||x.suggestion||guessType(x.file.name)})))}
  const assignedCount=pending.filter(x=>x.type).length,unassignedCount=pending.length-assignedCount
  async function process(){const assigned=pending.filter(x=>x.type);if(!assigned.length)return alert('Marque pelo menos um arquivo em uma categoria.');setProcessing(true);setOpenType(null);const messages:string[]=[],completed=new Set<string>();try{for(const[type,label]of docTypes){const items=assigned.filter(x=>x.type===type);if(!items.length)continue;const fd=new FormData();items.forEach(item=>fd.append('files',item.file,item.file.name));try{const r=await apiFetch('/api/import-classified?type='+encodeURIComponent(type),{method:'POST',body:fd}),j=await r.json();if(!r.ok)throw new Error(j.message||'Falha ao processar '+label);const results=j.results||[];const failed=new Set(results.filter((x:any)=>x.status==='ERROR').map((x:any)=>x.name));items.forEach(item=>{if(!failed.has(item.file.name))completed.add(item.key)});for(const result of results)messages.push(result.name+': '+(result.status==='IMPORTED'?'OK':result.detail||result.status||'processado'))}catch(e:any){messages.push(label+': '+e.message)}}setPending(items=>items.filter(x=>!completed.has(x.key)));await refresh();if(messages.length)alert(messages.join('\n'))}finally{setProcessing(false)}}
  const files=allSourceFiles||[]
  return <div className="page-content"><PageTitle eyebrow="ARQUIVOS" title="Entrada e orquestração dos dados" sub="Primeiro selecione os arquivos. Depois diga à Clara qual papel cada um exerce. Assim a leitura fica explícita e você pode usar mais de um arquivo para a mesma origem."/>
    <div className="v071-file-top"><div className="card v071-local-card"><CardHead title="Arquivos locais / OneDrive" sub="PDF, Excel ou CSV. Você pode selecionar uma pasta inteira ou adicionar arquivos avulsos." action={<div className="v071-local-actions"><button className="primary" disabled={!canWrite||processing} onClick={()=>folderRef.current?.click()}><FolderOpen/>Escolher pasta</button><button className="secondary" disabled={!canWrite||processing} onClick={()=>fileRef.current?.click()}><Plus/>Adicionar arquivos</button></div>}/><input ref={folderRef} hidden type="file" multiple {...({webkitdirectory:'true'} as any)} onChange={e=>{stage(e.target.files);e.currentTarget.value=''}}/><input ref={fileRef} hidden type="file" multiple accept=".pdf,.xlsx,.xls,.csv" onChange={e=>{stage(e.target.files);e.currentTarget.value=''}}/>{pending.length?<><div className="v071-local-summary"><div><b>{pending.length} arquivo(s) disponível(is)</b><span>{assignedCount} marcado(s) · {unassignedCount} ainda sem função definida</span></div><div className="v071-local-actions"><button className="secondary small" onClick={suggest}>Sugerir automaticamente</button><button className="secondary small" onClick={()=>{setPending([]);setOpenType(null)}}>Limpar seleção</button></div></div><div className="v071-pending-files">{pending.map((p:any)=><div className="v071-pending-file" key={p.key}><FileSpreadsheet/><div><b>{p.file.name}</b><small>{p.file.webkitRelativePath||Math.round(p.file.size/1024)+' KB'}{!p.type?' · sugestão: '+(docTypes.find(x=>x[0]===p.suggestion)?.[1]||'') : ''}</small></div><Pill tone={p.type?'blue':'gray'}>{p.type?docTypes.find(x=>x[0]===p.type)?.[1]:'Não definido'}</Pill><button className="icon-button" onClick={()=>setPending(items=>items.filter(x=>x.key!==p.key))}><X/></button></div>)}</div></>:<Empty icon={FolderOpen} title="Nenhuma pasta ou arquivo selecionado" sub="Escolha uma pasta ou adicione os documentos que deseja organizar."/>}</div>
      <div className="card v071-model-card"><CardHead title="Modelos Clara" sub="Para bases estruturadas de títulos"/><p>Contas a Pagar e Contas a Receber usam planilhas padronizadas. Extratos e faturas podem ser enviados em PDF, Excel ou CSV.</p><div className="v071-model-buttons"><button className="secondary" onClick={()=>download('/api/payables/template','modelo-contas-a-pagar-clara.xlsx').catch(e=>alert(e.message))}><Download/>Modelo Contas a Pagar</button><button className="secondary" onClick={()=>download('/api/receivables/template','modelo-contas-a-receber-clara.xlsx').catch(e=>alert(e.message))}><Download/>Modelo Contas a Receber</button></div></div></div>
    <div className="card v071-orchestration"><div className="v071-orchestration-intro"><div><b>Orquestração dos arquivos</b><p>À esquerda está o tipo de dado que a Clara entende. No centro, marque um ou mais arquivos. À direita, você vê o que já está efetivamente processado naquela origem.</p></div><div className="v071-orchestration-actions"><button className="primary" disabled={!canWrite||processing||!assignedCount} onClick={process}>{processing?<Spinner/>:<Upload/>}Processar marcados ({assignedCount})</button></div></div><div className="v071-orchestration-head"><span>Tipo de dado</span><span>Origem específica</span><span>Fonte efetivamente usada</span></div>{docTypes.map(([type,label])=>{const processed=files.filter((f:any)=>f.kind===type),selected=pending.filter(x=>x.type===type);return <div className="v071-orchestration-row" key={type}><div className="v071-orchestration-kind"><b>{label}</b><span>{orchestrationCopy[type]}</span></div><AssignmentPicker type={type} pending={pending} setPending={setPending} openType={openType} setOpenType={setOpenType}/><div className="v071-effective-source">{processed.slice(0,3).map((f:any)=>{const review=f.status!=='IMPORTED'||['MISMATCH','ERROR'].includes(f.validation_status);return <button type="button" key={f.id} className={'v071-source-chip '+(review?'review':'')} onClick={()=>setReviewFile(f.id)}><span>{f.name}</span>{review&&<AlertTriangle/>}</button>})}{processed.length>3&&<Pill tone="gray">+{processed.length-3}</Pill>}{selected.length>0&&<Pill tone="orange">{selected.length} aguardando processamento</Pill>}{!processed.length&&!selected.length&&<span className="v071-source-empty">Nenhuma fonte atribuída</span>}</div></div>})}<div className="v071-process-note"><CircleAlert/><span>Um arquivo só pode exercer um papel por vez. Ao marcá-lo em outra linha, a Clara move a atribuição automaticamente.</span></div></div>
    <div className="card"><div className="v071-history-title"><CardHead title="Histórico de arquivos processados" sub={files.length+' arquivo(s)'}/></div>{files.length?<div className="file-list">{files.map((f:any)=>{const review=f.status!=='IMPORTED'||['MISMATCH','ERROR'].includes(f.validation_status);return <button className={'file-row '+(review?'clickable':'')} key={f.id} onClick={()=>setReviewFile(f.id)}><div className="file-icon"><FileSpreadsheet/></div><div><b>{f.name}</b><span>{docTypes.find(x=>x[0]===f.kind)?.[1]||f.kind||'Arquivo'} · {f.record_count||0} lançamento(s)</span><small>{f.status_detail||'Processado'}{review?' · Clique para entender o alerta':''}</small></div><Pill tone={!review?'green':'orange'}>{!review?'Lido':'Revisar'}</Pill></button>})}</div>:<Empty icon={FileSpreadsheet} title="Nenhum arquivo processado" sub="Selecione seus arquivos acima e faça a orquestração."/>}</div>{reviewFile&&<FileDiagnostic fileId={reviewFile} onClose={()=>setReviewFile(null)} onChanged={refresh} onGoTransactions={onGoTransactions}/>}</div>
}

function ManualPayable`

const pattern=/export function FilesPageV070[\s\S]*?\n\nfunction ManualPayable/
if(!pattern.test(client))throw new Error('FilesPageV070 anchor not found')
client=client.replace(pattern,replacement)
fs.writeFileSync(clientPath,client)

const mainPath='client/src/main.tsx'
let main=fs.readFileSync(mainPath,'utf8')
main=main.replace("const APP_VERSION='0.7.0'","const APP_VERSION='0.7.1'")
fs.writeFileSync(mainPath,main)

const serverPath='server/src/index.ts'
let server=fs.readFileSync(serverPath,'utf8')
server=server.replaceAll("version:'0.7.0'","version:'0.7.1'").replace('Clara BPO v0.7.0 on','Clara BPO v0.7.1 on')
fs.writeFileSync(serverPath,server)

console.log('v0.7.1 file orchestration integration applied')
